/**
 * apps/modules/tabs-config.js — Реестр определений вкладок для интерфейса /apps
 */

export const APP_TAB_DEFS = [
  { id: 'about_system', label: 'О Системе', icon: 'ℹ️', tab: 'about-system', tabId: 'tab-about-system', html: '/html/about_system_tab/index.html?v=20260926_v1', js: '/html/about_system_tab/main.js?v=20260926_v1' },
  { id: 'scenarios', label: 'Чат и сценарии', icon: '💬', tab: 'scenarios', tabId: 'tab-scenarios', html: '/html/scenarios_tab/index.html?v=20260925_v2', js: '/html/scenarios_tab/main.js?v=20260925_v2' },
  { id: 'chat', label: 'Чат', icon: '💬', tab: 'chat', tabId: 'tab-chat', html: '/html/chat/index.html?v=20260923_v5', js: '/html/chat/main.js?v=20260923_v5' },
  { id: 'network_terminal', label: 'Сетевой терминал', icon: '🌐', tab: 'network', tabId: 'tab-network', html: '/html/network_tab/index.html', js: '/html/network_tab/main.js' },
  { id: 'system_inspector', label: 'Потребление ресурсов', icon: 'bi-graph-up-arrow', tab: 'system-inspector', tabId: 'tab-system-inspector', html: '/html/system_inspector_tab/index.html?v=20260926_v1', js: '/html/system_inspector_tab/main.js?v=20260926_v1' },
  { id: 'windows_sysadmin', label: 'Windows Sysadmin', icon: 'bi-server', tab: 'windows-admin', tabId: 'tab-windows-admin', html: '/html/windows_admin_tab/index.html', js: '/html/windows_admin_tab/main.js' },
  { id: 'system_control_center', label: 'System Control', icon: 'bi-tools', tab: 'system-control', tabId: 'tab-system-control', html: '/html/system_control_tab/index.html?v=20260925_v1', js: '/html/system_control_tab/main.js?v=20260925_v1' },
  { id: 'system_log_viewer', label: 'Системные логи', icon: '📋', tab: 'system-logs', tabId: 'tab-system-logs', html: '/html/system_logs_tab/index.html', js: '/html/system_logs_tab/main.js' },
  { id: 'software_audit', label: 'Аудит программ', icon: '📦', tab: 'software-audit', tabId: 'tab-software-audit', html: '/html/software_audit_tab/index.html', js: '/html/software_audit_tab/main.js' },
  { id: 'registry_viewer', label: 'Registry Viewer', icon: '🗝️', tab: 'registry-viewer', tabId: 'tab-registry-viewer', html: '/html/registry_viewer_tab/index.html', js: '/html/registry_viewer_tab/main.js' },
  { id: 'windows_defender', label: 'Defender Security', icon: 'bi-shield-lock', tab: 'defender', tabId: 'tab-defender', html: '/html/defender_tab/index.html', js: '/html/defender_tab/main.js' },
  { id: 'windows_startup_auditor', label: 'Автозапуск программ', icon: '🚀', tab: 'startup-auditor', tabId: 'tab-startup-auditor', html: '/html/startup_auditor_tab/index.html', js: '/html/startup_auditor_tab/main.js' },
  { id: 'windows_backup_manager', label: 'Windows Backup', icon: '💾', tab: 'windows-backup', tabId: 'tab-windows-backup', html: '/html/windows_backup_tab/index.html?v=20260924_v2', js: '/html/windows_backup_tab/main.js?v=20260924_v2' },
  { id: 'hardware_monitor', label: 'Мониторинг железа', icon: 'bi-cpu', tab: 'hardware-monitor', tabId: 'tab-hardware-monitor', html: '/html/hardware_monitor_tab/index.html', js: '/html/hardware_monitor_tab/main.js' },
  { id: 'cloudflared_monitor', label: 'Cloudflared', icon: '☁️', tab: 'cloudflared', tabId: 'tab-cloudflared', html: '/html/cloudflared_tab/index.html', js: '/html/cloudflared_tab/main.js' },
  { id: 'gcloud_monitor', label: 'Google Cloud', icon: '☁️', tab: 'gcloud', tabId: 'tab-gcloud', html: '/html/gcloud_tab/index.html', js: '/html/gcloud_tab/main.js' },
  { id: 'website_monitor', label: 'Website Intelligence', icon: '📊', tab: 'website-monitor', tabId: 'tab-website-monitor', html: '/html/website_monitor_tab/index.html', js: '/html/website_monitor_tab/main.js' },
  { id: 'trading_terminal', label: 'Trading Terminal', icon: '📈', tab: 'trading', tabId: 'tab-trading', html: '/html/trading_tab/index.html', js: '/html/trading_tab/main.js' },
  { id: 'user_assistant', label: 'User Assistant', icon: '🗓️', tab: 'user-assistant', tabId: 'tab-user-assistant', html: '/html/user_assistant_tab/index.html', js: '/html/user_assistant_tab/main.js' },
  { id: 'helpdesk', label: 'Helpdesk', icon: '🎫', tab: 'helpdesk', tabId: 'tab-helpdesk', html: '/html/helpdesk_tab/index.html', js: '/html/helpdesk_tab/main.js' },
  { id: 'wikipedia_research', label: 'Wikipedia Research', icon: '📖', tab: 'wikipedia-research', tabId: 'tab-wikipedia-research', html: '/html/wikipedia_research_tab/index.html', js: '/html/wikipedia_research_tab/main.js' },
  { id: 'autolog_manager', label: 'Автолог', icon: '📝', tab: 'autolog', tabId: 'tab-autolog', html: '/html/autolog_tab/index.html?v=20260925_v2', js: '/html/autolog_tab/main.js?v=20260925_v2' },
  { id: 'software_transparency_scanner', label: 'Transparency Scanner', icon: '🔍', tab: 'software-transparency', tabId: 'tab-software-transparency', html: '/html/software_transparency_tab/index.html?v=20260926_v2', js: '/html/software_transparency_tab/main.js?v=20260926_v2' },
  { id: 'user_directories', label: 'Пользовательские папки', icon: '📁', tab: 'user-directories', tabId: 'tab-user-directories', html: '/html/user_directories_tab/index.html', js: '/html/user_directories_tab/main.js' },
  { id: 'ninite_updater', label: 'Ninite Updater', icon: '🔄', tab: 'ninite-updater', tabId: 'tab-ninite-updater', html: '/html/ninite_updater_tab/index.html?v=20260924_v2', js: '/html/ninite_updater_tab/main.js?v=20260924_v2' },
  { id: 'file_recovery', label: 'Восстановление файлов', icon: '🩹', tab: 'file-recovery', tabId: 'tab-file-recovery', html: '/html/file_recovery_tab/index.html', js: '/html/file_recovery_tab/main.js' },
  { id: 'telemetry_history', label: 'История телеметрии', icon: 'bi-graph-up', tab: 'telemetry-history', tabId: 'tab-telemetry-history', html: '/html/telemetry_history_tab/index.html?v=20260924_v1', js: '/html/telemetry_history_tab/main.js?v=20260924_v1' },
  { id: 'telemetry_research', label: 'Анализ телеметрии', icon: '🔬', tab: 'telemetry-research', tabId: 'tab-telemetry-research', html: '/html/telemetry_research_tab/index.html?v=20260924_v1', js: '/html/telemetry_research_tab/main.js?v=20260924_v1' },
  { id: 'process_leaks', label: 'Утечки процессов', icon: '⚠️', tab: 'process-leaks', tabId: 'tab-process-leaks', html: '/html/process_leaks_tab/index.html?v=20260924_v1', js: '/html/process_leaks_tab/main.js?v=20260924_v1' },
  { id: 'forensics', label: 'Форензика', icon: '🛡️', tab: 'forensics', tabId: 'tab-forensics', html: '/html/forensics_tab/index.html?v=20260924_v1', js: '/html/forensics_tab/main.js?v=20260924_v1' },
  { id: 'throttling', label: 'Троттлинг', icon: '🌡️', tab: 'throttling', tabId: 'tab-throttling', html: '/html/throttling_tab/index.html?v=20260924_v1', js: '/html/throttling_tab/main.js?v=20260924_v1' },
  { id: 'storage_wear', label: 'Износ дисков', icon: '💽', tab: 'storage-wear', tabId: 'tab-storage-wear', html: '/html/storage_wear_tab/index.html?v=20260924_v1', js: '/html/storage_wear_tab/main.js?v=20260924_v1' },
  { id: 'peripherals', label: 'Периферия', icon: '🔌', tab: 'peripherals', tabId: 'tab-peripherals', html: '/html/peripherals_tab/index.html?v=20260924_v1', js: '/html/peripherals_tab/main.js?v=20260924_v1' },
  { id: 'rag', label: 'RAG Знания', icon: '🧠', tab: 'rag', tabId: 'tab-rag', html: '/html/rag_tab/index.html', js: '/html/rag_tab/main.js' },
  { id: 'pixelrag', label: 'PixelRAG', icon: '🖼️', tab: 'pixelrag', tabId: 'tab-pixelrag', html: '/html/pixelrag_tab/index.html', js: '/html/pixelrag_tab/main.js' },
  { id: 'models', label: 'Модели ИИ', icon: '🤖', tab: 'models', tabId: 'tab-models', html: '/html/models_tab/index.html', js: '/html/models_tab/main.js' },
  { id: 'agents', label: 'Агенты ИИ', icon: '🧩', tab: 'agents', tabId: 'tab-agents', html: '/html/agents_tab/index.html', js: '/html/agents_tab/main.js' },
  { id: 'skills', label: 'Навыки ИИ', icon: '⚡', tab: 'skills', tabId: 'tab-skills', html: '/html/skills_tab/index.html', js: '/html/skills_tab/main.js' },
  { id: 'mcp', label: 'MCP Серверы', icon: '🔌', tab: 'mcp', tabId: 'tab-mcp', html: '/html/mcp_tab/index.html', js: '/html/mcp_tab/main.js' },
  { id: 'ai_benchmark', label: 'AI Benchmark', icon: '⏱️', tab: 'ai-benchmark', tabId: 'tab-ai-benchmark', html: '/html/ai_benchmark_tab/index.html?v=20260926_v1', js: '/html/ai_benchmark_tab/main.js?v=20260926_v1' },
];

export const TC_EXCLUDES = new Set([
  'cloudflared_monitor',
  'gcloud_monitor',
  'website_monitor',
  'user_assistant',
  'wikipedia_research',
  'trading_terminal',
  'helpdesk'
]);
