# -*- coding: utf-8 -*-
# =============================================================================
# Process Name: AI-Breadboard Apps Windows Core - Build Command Registry
# =============================================================================
# Description:
#   Скрипт генерации полного реестра штатных команд Windows 10/11
#   (66 категорий, Control Planes, Telemetry Tiers, эквиваленты Win32/PS/WMI/COM).
#
# Usage Examples:
#   python apps/windows/core/build_command_registry.py
#
# File: build_command_registry.py
# Project: ai-breadboard
# Package: apps.windows.core
# Author: hypo69
# Copyright: © 2026 hypo69
# Updated: 2026-10-06 15:15:00
# =============================================================================

import json
from pathlib import Path

DATA_PATH = Path(__file__).resolve().parent / 'data' / 'windows_command_registry.json'

def build_catalog():
    items = []

    def add(exe, cat, code, purpose, access, priv, danger, tier, plane,
            ps=None, wmi=None, win32=None, nt=None, com=None, etw=None, evtx=None,
            unattended=True, monitor=False, modify=False, gui=False, msc=False, cpl=False, builtin=False,
            etw_pipe=False, usn=False, templates=None, subcommands=None, sub_tree=None, route=None, tags=None):
        clean_name = exe.lower().replace('.exe', '').replace('.com', '').replace('.msc', '').replace('.cpl', '').replace(':', '')
        items.append({
            "executable": exe,
            "category": cat,
            "category_code": code,
            "purpose": purpose,
            "access_type": access,
            "required_privileges": priv,
            "danger_level": danger,
            "telemetry_tier": tier,
            "primary_control_plane": plane,
            "powershell_equivalent": ps,
            "wmi_cim_equivalent": wmi,
            "native_api_equivalent": win32,
            "native_nt_api_equivalent": nt,
            "com_equivalent": com,
            "etw_provider_equivalent": etw,
            "event_log_channel_equivalent": evtx,
            "can_run_unattended": unattended,
            "can_monitor": monitor,
            "can_modify_system": modify,
            "is_gui": gui,
            "is_msc_console": msc,
            "is_cpl_applet": cpl,
            "is_cmd_builtin": builtin,
            "etw_pipeline_enabled": etw_pipe,
            "usn_journal_enabled": usn,
            "command_templates": templates or [],
            "subcommands_info": subcommands or {},
            "subcommands_tree": sub_tree or {},
            "rest_endpoint": route or f"/api/v1/system32/tool/{clean_name}",
            "tags": tags or []
        })

    # 01. SHELLS & COMMAND EXECUTION
    add("cmd.exe", "shells_execution", "01. SHELLS & COMMAND EXECUTION", "Интерпретатор командной строки Windows (Command Prompt).", "READ_WRITE", "STANDARD", "HIGH", "CONTROL", "CLI", ps="Invoke-Expression / Start-Process", wmi="Win32_Process.Create", win32="CreateProcessW", nt="NtCreateUserProcess", templates=["cmd.exe /c \"{cmd}\""], tags=["shell", "cli", "batch"])
    add("powershell.exe", "shells_execution", "01. SHELLS & COMMAND EXECUTION", "Среда объектного сценария и автоматизации Windows PowerShell 5.1.", "READ_WRITE", "STANDARD", "HIGH", "CONTROL", "POWERSHELL", ps="Internal Engine", win32="System.Management.Automation", templates=["powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"{cmd}\""], tags=["powershell", "automation"])
    add("pwsh.exe", "shells_execution", "01. SHELLS & COMMAND EXECUTION", "Современный кроссплатформенный PowerShell Core 7+.", "READ_WRITE", "STANDARD", "HIGH", "CONTROL", "POWERSHELL", ps="Internal Engine", templates=["pwsh.exe -NoProfile -Command \"{cmd}\""], tags=["pwsh", "powershell7"])
    add("wscript.exe", "shells_execution", "01. SHELLS & COMMAND EXECUTION", "Оконный исполнитель скриптов Windows Script Host (VBScript/JScript).", "READ_WRITE", "STANDARD", "MEDIUM", "CONTROL", "COM", com="WScript.Shell", gui=True, templates=["wscript.exe \"{script_file}\""], tags=["wscript", "vbs", "js"])
    add("cscript.exe", "shells_execution", "01. SHELLS & COMMAND EXECUTION", "Консольный исполнитель скриптов Windows Script Host (CLI).", "READ_WRITE", "STANDARD", "MEDIUM", "CONTROL", "CLI", com="WScript.Shell", templates=["cscript.exe //NoLogo \"{script_file}\""], tags=["cscript", "vbs", "js"])
    add("mshta.exe", "shells_execution", "01. SHELLS & COMMAND EXECUTION", "Исполнитель HTML-приложений (Microsoft HTML Application Host).", "READ_WRITE", "STANDARD", "HIGH", "CONTROL", "GUI_MMC_CPL", gui=True, templates=["mshta.exe \"{hta_url_or_file}\""], tags=["hta", "html"])
    add("rundll32.exe", "shells_execution", "01. SHELLS & COMMAND EXECUTION", "Запуск экспортируемых Win32 DLL функций из командной строки.", "READ_WRITE", "STANDARD", "HIGH", "CONTROL", "WIN32_API", win32="LoadLibraryW + GetProcAddress", templates=["rundll32.exe {dll},{entry_point}"], tags=["dll", "rundll32"])
    add("regsvr32.exe", "shells_execution", "01. SHELLS & COMMAND EXECUTION", "Регистрация и дерегистрация OLE/COM серверов и элементов управления DLL/OCX.", "WRITE", "ADMINISTRATOR", "HIGH", "ADMIN", "COM", win32="DllRegisterServer / DllUnregisterServer", modify=True, templates=["regsvr32.exe /s \"{dll_path}\"", "regsvr32.exe /u /s \"{dll_path}\""], tags=["com", "dll-registration"])
    add("where.exe", "shells_execution", "01. SHELLS & COMMAND EXECUTION", "Поиск местоположения исполняемых файлов по системному PATH.", "READ", "STANDARD", "SAFE", "OBSERVE", "CLI", ps="Get-Command {cmd} | Select-Object -ExpandProperty Source", monitor=True, templates=["where.exe {pattern}"], tags=["search", "path", "discovery"])
    add("wt.exe", "shells_execution", "01. SHELLS & COMMAND EXECUTION", "Современный терминал Windows Terminal.", "READ_WRITE", "STANDARD", "LOW", "CONTROL", "GUI_MMC_CPL", gui=True, templates=["wt.exe"], tags=["terminal", "wt"])

    # 02. FILES & DIRECTORIES
    add("attrib.exe", "files_directories", "02. FILES & DIRECTORIES", "Просмотр и изменение атрибутов файлов (R, A, S, H, I, X, V, P, U).", "READ_WRITE", "STANDARD", "LOW", "CONTROL", "WIN32_API", ps="Get-ItemProperty / Set-ItemProperty -Name Attributes", win32="GetFileAttributesW / SetFileAttributesW", modify=True, templates=["attrib.exe +R \"{path}\"", "attrib.exe -H -S \"{path}\""], tags=["files", "attributes"])
    add("icacls.exe", "files_directories", "02. FILES & DIRECTORIES", "Управление списками управления доступом ACL к файлам и папкам.", "READ_WRITE", "ADMINISTRATOR", "HIGH", "ADMIN", "WIN32_API", ps="Get-Acl / Set-Acl", win32="GetNamedSecurityInfoW / SetNamedSecurityInfoW", modify=True, subcommands={"/grant": "Предоставление прав", "/deny": "Запрет прав", "/save": "Бэкап ACL", "/restore": "Восстановление ACL"}, templates=["icacls.exe \"{path}\" /grant {user}:F", "icacls.exe \"{path}\" /save acl_backup.txt"], tags=["acl", "security", "permissions"])
    add("takeown.exe", "files_directories", "02. FILES & DIRECTORIES", "Смена владельца файла или директории на текущего пользователя или администраторов.", "WRITE", "ADMINISTRATOR", "HIGH", "ADMIN", "WIN32_API", ps="Set-Acl -Owner", win32="SetNamedSecurityInfoW(OWNER_SECURITY_INFORMATION)", modify=True, templates=["takeown.exe /f \"{path}\" /r /d y"], tags=["takeown", "ownership", "security"])
    add("robocopy.exe", "files_directories", "02. FILES & DIRECTORIES", "Надежное многопоточное копирование файлов и структуры каталогов (Robust File Copy).", "READ_WRITE", "STANDARD", "LOW", "CONTROL", "WIN32_API", ps="Copy-Item", win32="CopyFileExW", modify=True, templates=["robocopy.exe \"{src}\" \"{dst}\" /MIR /R:2 /W:5 /MT:16 /LOG:copy.log"], tags=["backup", "copy", "robocopy", "sync"])
    add("fc.exe", "files_directories", "02. FILES & DIRECTORIES", "Сравнение содержимого двух файлов (текстовое или бинарное).", "READ", "STANDARD", "SAFE", "OBSERVE", "CLI", ps="Compare-Object", monitor=True, templates=["fc.exe /b \"{file1}\" \"{file2}\""], tags=["diff", "compare"])
    add("findstr.exe", "files_directories", "02. FILES & DIRECTORIES", "Поиск строк и регулярных выражений в файлах и потоках текста (Grep для Windows).", "READ", "STANDARD", "SAFE", "OBSERVE", "CLI", ps="Select-String", monitor=True, templates=["findstr.exe /s /i /n \"{pattern}\" *.*"], tags=["grep", "search", "regex"])
    add("makecab.exe", "archiving_packaging", "47. ARCHIVING / PACKAGING", "Архиватор Microsoft Cabinet (.cab).", "WRITE", "STANDARD", "LOW", "CONTROL", "CLI", modify=True, templates=["makecab.exe \"{src}\" \"{dst}.cab\""], tags=["cab", "compression", "archive"])
    add("expand.exe", "archiving_packaging", "47. ARCHIVING / PACKAGING", "Распаковщик сжатых файлов и архивов Cabinet (.cab, .ex_).", "READ_WRITE", "STANDARD", "LOW", "CONTROL", "CLI", modify=True, templates=["expand.exe \"{src}.cab\" -F:* \"{dst}\""], tags=["cab", "extract", "expand"])
    add("extrac32.exe", "archiving_packaging", "47. ARCHIVING / PACKAGING", "Графический и консольный инструмент извлечения CAB архивов.", "READ_WRITE", "STANDARD", "LOW", "CONTROL", "CLI", modify=True, templates=["extrac32.exe /Y /E \"{cab_file}\""], tags=["cab", "extrac32"])

    # 03. STORAGE / DISKS
    add("diskpart.exe", "storage_disks", "03. STORAGE / DISKS", "Низкоуровневое управление дисками, разметкой GPT/MBR, разделами, томами и VHD.", "READ_WRITE", "ADMINISTRATOR", "CRITICAL", "DESTRUCTIVE", "CLI", ps="Get-Disk / Initialize-Disk / New-Partition / Format-Volume", wmi="MSFT_Disk / MSFT_Partition / MSFT_Volume", win32="DeviceIoControl(IOCTL_DISK_*)", com="IVdsService", modify=True, subcommands={"list disk": "Список физических дисков", "list volume": "Список томов", "select disk": "Выбор диска", "clean": "Полное стирание разметки", "create partition": "Создание раздела", "format": "Форматирование тома", "attach vdisk": "Монтирование виртуального диска VHD", "compact vdisk": "Сжатие VHD"}, sub_tree={"disk": ["list", "select", "clean", "convert gpt", "convert mbr", "detail", "offline", "online"], "partition": ["list", "select", "create primary", "create efi", "delete", "extend", "shrink"], "volume": ["list", "select", "format", "assign", "remove", "detail"], "vdisk": ["attach", "detach", "compact", "expand", "merge"]}, templates=["diskpart.exe /s \"{script_file}\""], tags=["storage", "disk", "partition", "vhd", "gpt"])
    add("fsutil.exe", "storage_disks", "03. STORAGE / DISKS", "Расширенное управление параметрами NTFS, журналом изменений USN, квотами, TRIM и томами.", "READ_WRITE", "ADMINISTRATOR", "MEDIUM", "CONTROL", "CLI", ps="Get-Volume / Set-Volume", win32="FSCTL_* APIs", modify=True, monitor=True, usn=True, subcommands={"fsinfo": "Сведения о файловой системе", "usn": "Управление NTFS USN журналом", "behavior": "Настройка TRIM и генерации 8.3", "dirty": "Проверка dirty bit тома", "volume": "Управление томами и свободным местом", "quota": "Квоты диска"}, sub_tree={"fsinfo": ["drives", "drivetype", "volumeinfo", "ntfsinfo", "statistics"], "usn": ["queryjournal", "createjournal", "deletejournal", "readjournal", "enumnodata"], "behavior": ["query DisableDeleteNotify", "set DisableDeleteNotify 0", "query disable8dot3"], "dirty": ["query", "set"]}, templates=["fsutil.exe fsinfo volumeinfo {drive}:", "fsutil.exe usn queryjournal {drive}:", "fsutil.exe behavior query DisableDeleteNotify"], tags=["ntfs", "usn-journal", "trim", "filesystem", "telemetry"])
    add("diskperf.exe", "storage_disks", "03. STORAGE / DISKS", "Управление счетчиками производительности дисков (Disk Performance Counters).", "READ_WRITE", "ADMINISTRATOR", "LOW", "OBSERVE", "WIN32_API", modify=True, monitor=True, templates=["diskperf.exe -y", "diskperf.exe -n"], tags=["diskperf", "perf-counters", "storage"])
    add("diskshadow.exe", "storage_disks", "03. STORAGE / DISKS", "Управление снимками и теневыми копиями томов через VSS командную строку.", "READ_WRITE", "ADMINISTRATOR", "HIGH", "ADMIN", "COM", com="IVssBackupComponents", modify=True, monitor=True, templates=["diskshadow.exe /s \"{script_file}\""], tags=["diskshadow", "vss", "snapshot"])
    add("chkdsk.exe", "storage_disks", "03. STORAGE / DISKS", "Проверка целостности метаданных файловой системы и исправление повреждений секторов.", "READ_WRITE", "ADMINISTRATOR", "HIGH", "RECOVERY", "WIN32_API", ps="Repair-Volume", win32="Chkdsk / FMIFS.dll", modify=True, monitor=True, templates=["chkdsk.exe {drive}: /scan", "chkdsk.exe {drive}: /F /R"], tags=["chkdsk", "fs-repair", "bad-sectors", "integrity"])
    add("chkntfs.exe", "storage_disks", "03. STORAGE / DISKS", "Управление автоматической проверкой файловой системы при загрузке системы.", "READ_WRITE", "ADMINISTRATOR", "MEDIUM", "CONTROL", "WIN32_API", modify=True, templates=["chkntfs.exe {drive}:", "chkntfs.exe /x {drive}:"], tags=["chkntfs", "boot-check", "dirty-bit"])
    add("defrag.exe", "storage_disks", "03. STORAGE / DISKS", "Оптимизация и дефрагментация дисков (HDD defrag / SSD retrim).", "WRITE", "ADMINISTRATOR", "LOW", "CONTROL", "WIN32_API", ps="Optimize-Volume -DriveLetter {drive} -Defrag", win32="FSCTL_MOVE_FILE", modify=True, templates=["defrag.exe {drive}: /O /V"], tags=["defrag", "optimize", "ssd-retrim"])
    add("format.com", "storage_disks", "03. STORAGE / DISKS", "Форматирование разделов и томов в NTFS, FAT32, exFAT, ReFS.", "WRITE", "ADMINISTRATOR", "CRITICAL", "DESTRUCTIVE", "WIN32_API", ps="Format-Volume -DriveLetter {drive} -FileSystem NTFS -Quick", win32="FormatVolumeEx (fmifs.dll)", modify=True, templates=["format.com {drive}: /FS:{fs} /Q /Y /V:{label}"], tags=["format", "filesystem", "erase", "storage"])
    add("mountvol.exe", "storage_disks", "03. STORAGE / DISKS", "Создание, удаление и просмотр точек монтирования томов и GUID-путей.", "READ_WRITE", "ADMINISTRATOR", "MEDIUM", "CONTROL", "WIN32_API", ps="Get-Partition / Add-PartitionAccessPath", win32="FindFirstVolumeW / SetVolumeMountPointW", modify=True, templates=["mountvol.exe", "mountvol.exe {path} {volume}", "mountvol.exe {drive}: /D"], tags=["mount", "guid", "volume", "mountpoint"])
    add("refsutil.exe", "storage_disks", "03. STORAGE / DISKS", "Диагностика и восстановление устойчивой файловой системы ReFS (Resilient File System).", "READ_WRITE", "ADMINISTRATOR", "HIGH", "RECOVERY", "WIN32_API", modify=True, monitor=True, templates=["refsutil.exe salvage -d {drive}: -w {target}"], tags=["refs", "refsutil", "resilient-fs", "salvage"])
    add("vssadmin.exe", "vss_backup", "06. VOLUME SHADOW COPY / BACKUP", "Администрирование службы теневого копирования томов VSS (Volume Shadow Copy).", "READ_WRITE", "ADMINISTRATOR", "HIGH", "ADMIN", "COM", ps="Get-CimInstance Win32_ShadowCopy", com="IVssBackupComponents", modify=True, monitor=True, subcommands={"list shadows": "Список всех теневых копий", "list writers": "Список VSS писателей", "list shadowstorage": "Хранилище VSS", "resize shadowstorage": "Изменение объема", "delete shadows": "Удаление снимков"}, templates=["vssadmin.exe list shadows", "vssadmin.exe list writers", "vssadmin.exe list shadowstorage"], tags=["vss", "shadow-copy", "backup", "snapshot"])
    add("wbadmin.exe", "backup_restore", "62. BACKUP / RESTORE", "Управление резервным копированием и восстановлением Windows Server Backup / System Image.", "READ_WRITE", "ADMINISTRATOR", "CRITICAL", "RECOVERY", "CLI", ps="Start-WBBackup / Get-WBBackupSet", modify=True, monitor=True, subcommands={"start backup": "Запуск бэкапа", "get versions": "Список версий", "start recovery": "Запуск восстановления"}, templates=["wbadmin.exe get versions", "wbadmin.exe start backup -backupTarget:{target} -include:{drives} -allCritical -quiet"], tags=["wbadmin", "backup", "system-image", "recovery"])
    add("manage-bde.exe", "bitlocker_encryption", "05. BITLOCKER / ENCRYPTION", "Управление шифрованием дисков BitLocker Drive Encryption и ключами в TPM.", "READ_WRITE", "ADMINISTRATOR", "CRITICAL", "ADMIN", "WMI_CIM", ps="Get-BitLockerVolume / Enable-BitLocker / Unlock-BitLocker", wmi="Win32_EncryptableVolume", modify=True, monitor=True, subcommands={"-status": "Статус шифрования всех дисков", "-protectors -get": "Просмотр паролей восстановления", "-lock": "Блокировка тома"}, templates=["manage-bde.exe -status", "manage-bde.exe -protectors -get {drive}:"], tags=["bitlocker", "encryption", "tpm", "security"])
    add("repair-bde.exe", "bitlocker_encryption", "05. BITLOCKER / ENCRYPTION", "Восстановление зашифрованного тома BitLocker с поврежденной структурой.", "READ_WRITE", "ADMINISTRATOR", "CRITICAL", "RECOVERY", "CLI", modify=True, templates=["repair-bde.exe {source_drive}: {target_drive}: -rp {recovery_password}"], tags=["bitlocker", "repair-bde", "recovery", "encryption"])
    add("certutil.exe", "certificates_pki", "39. CERTIFICATES / PKI", "Управление сертификатами X.509, хранилищами PKI, хэшированием файлов и кодированием Base64.", "READ_WRITE", "STANDARD", "MEDIUM", "OBSERVE", "WIN32_API", ps="Get-ChildItem Cert:\\ / Get-FileHash", win32="CryptStringToBinaryW / CertOpenSystemStoreW", monitor=True, subcommands={"-hashfile": "Вычисление MD5/SHA1/SHA256 хеша", "-dump": "Дамп сертификата", "-store": "Просмотр хранилища сертификатов", "-encode": "Base64 кодирование"}, templates=["certutil.exe -hashfile \"{file}\" SHA256", "certutil.exe -store My", "certutil.exe -encode \"{src}\" \"{dst}\""], tags=["certutil", "hash", "sha256", "certificates", "crypto", "base64"])

    # 07. PROCESSES & 32. DRIVERS
    add("tasklist.exe", "processes", "07. PROCESSES", "Отображение списка выполняющихся процессов, их PID, сессий и потребления ОЗУ.", "READ", "STANDARD", "SAFE", "OBSERVE", "WIN32_API", ps="Get-Process", wmi="Win32_Process", win32="CreateToolhelp32Snapshot / EnumProcesses", monitor=True, templates=["tasklist.exe /FO CSV /V", "tasklist.exe /M", "tasklist.exe /SVC"], tags=["process", "tasklist", "diagnostics", "telemetry"])
    add("taskkill.exe", "processes", "07. PROCESSES", "Принудительное или грациозное завершение процессов и деревьев процессов.", "WRITE", "STANDARD", "HIGH", "CONTROL", "WIN32_API", ps="Stop-Process -Id {pid} -Force", wmi="Win32_Process.Terminate", win32="TerminateProcess / OpenProcess", modify=True, templates=["taskkill.exe /F /PID {pid}", "taskkill.exe /F /T /IM {image_name}"], tags=["process", "taskkill", "kill", "terminate"])
    add("qprocess.exe", "processes", "07. PROCESSES", "Быстрый запрос процессов терминального сервера и локальных сессий (Query Process).", "READ", "STANDARD", "SAFE", "OBSERVE", "WIN32_API", win32="WTSEnumerateProcessesW", monitor=True, templates=["qprocess.exe *"], tags=["process", "rdp", "session", "qprocess"])
    add("tskill.exe", "processes", "07. PROCESSES", "Завершение процессов пользователя или сессии терминала (Terminal Server Kill).", "WRITE", "STANDARD", "HIGH", "CONTROL", "WIN32_API", win32="WTSLogoffSession / TerminateProcess", modify=True, templates=["tskill.exe {pid}"], tags=["process", "tskill", "rdp"])
    add("openfiles.exe", "processes", "07. PROCESSES", "Отображение и отключение открытых файлов и сетевых папок.", "READ_WRITE", "ADMINISTRATOR", "MEDIUM", "OBSERVE", "WIN32_API", win32="NetFileEnum / NtQueryInformationFile", modify=True, monitor=True, templates=["openfiles.exe /query /fo csv"], tags=["openfiles", "files", "locks", "smb"])
    add("driverquery.exe", "drivers", "32. DRIVERS", "Таблица установленных и загруженных драйверов ядра, типов и даты линковки.", "READ", "STANDARD", "SAFE", "OBSERVE", "WIN32_API", ps="Get-WindowsDriver", win32="EnumDeviceDrivers / GetDeviceDriverBaseNameW", monitor=True, templates=["driverquery.exe /fo csv /v"], tags=["drivers", "driverquery", "kernel", "telemetry"])
    add("pnputil.exe", "device_pnp", "33. DEVICE / PNP", "Управление пакетами драйверов PnP в хранилище DriverStore и устройствами.", "READ_WRITE", "ADMINISTRATOR", "HIGH", "CONTROL", "WIN32_API", ps="Get-PnpDevice / Export-WindowsDriver", win32="SetupAPI / CfgMgr32", modify=True, monitor=True, subcommands={"/enum-devices": "Список PnP устройств", "/enum-drivers": "Список драйверов в DriverStore", "/add-driver": "Добавление INF драйвера", "/delete-driver": "Удаление драйвера"}, templates=["pnputil.exe /enum-devices /problem", "pnputil.exe /enum-drivers"], tags=["pnp", "pnputil", "driverstore", "hardware"])
    add("verifier.exe", "driver_verifier", "34. DRIVER VERIFIER", "Диспетчер проверки драйверов ядра Windows Driver Verifier (поиск BSOD / утечек пула).", "READ_WRITE", "ADMINISTRATOR", "HIGH", "DIAGNOSE", "GUI_MMC_CPL", gui=True, modify=True, templates=["verifier.exe /standard /all", "verifier.exe /reset", "verifier.exe /query"], tags=["verifier", "bsod", "kernel", "driver-debug"])
    add("fltmc.exe", "drivers", "32. DRIVERS", "Управление драйверами фильтров файловой системы (Minifilters Manager).", "READ_WRITE", "ADMINISTRATOR", "HIGH", "OBSERVE", "WIN32_API", win32="FilterFindFirst / FilterLoad", modify=True, monitor=True, subcommands={"filters": "Список активных минифильтров", "instances": "Экземпляры фильтров", "volumes": "Тома под контролем фильтров"}, templates=["fltmc.exe filters", "fltmc.exe instances"], tags=["minifilter", "fltmc", "antivirus", "fs-filter"])

    # 16. ETW / PERFORMANCE / TRACING
    add("logman.exe", "etw_performance_tracing", "16. ETW / PERFORMANCE / TRACING", "Управление сессиями Event Tracing for Windows (ETW) и сборщиками данных производительности Performance Logs.", "READ_WRITE", "ADMINISTRATOR", "MEDIUM", "CONTROL", "ETW", ps="Get-Counter / New-NetEventSession", win32="StartTraceW / ControlTraceW / Pdh API", etw="ETW Session Engine", modify=True, monitor=True, etw_pipe=True, subcommands={"query": "Список Data Collector Sets", "query -ets": "Список активных сессий ETW трассировки", "start": "Запуск сессии", "stop": "Остановка сессии", "create": "Создание сборщика данных"}, templates=["logman.exe query", "logman.exe query -ets", "logman.exe start {session} -ets", "logman.exe stop {session} -ets"], tags=["etw", "logman", "telemetry-core", "perfmon", "tracing"])
    add("typeperf.exe", "etw_performance_tracing", "16. ETW / PERFORMANCE / TRACING", "Сбор системных счетчиков производительности в реальном времени напрямую в консоль или CSV.", "READ", "STANDARD", "SAFE", "OBSERVE", "WIN32_API", ps="Get-Counter", win32="PdhCollectQueryData / pdh.dll", monitor=True, etw_pipe=True, templates=["typeperf.exe \"\\Processor(_Total)\\% Processor Time\" -si 2 -sc 5", "typeperf.exe -qx"], tags=["performance", "metrics", "typeperf", "realtime"])
    add("tracerpt.exe", "etw_performance_tracing", "16. ETW / PERFORMANCE / TRACING", "Парсинг и преобразование бинарных логов событий ETW (.etl) и счетчиков в форматы CSV/XML/HTML.", "READ", "STANDARD", "SAFE", "OBSERVE", "ETW", ps="Get-WinEvent -Path {etl}", win32="OpenTraceW / ProcessTrace", monitor=True, etw_pipe=True, templates=["tracerpt.exe \"{trace_etl}\" -o \"{output_csv}\" -of CSV -summary \"{summary_txt}\""], tags=["tracerpt", "etl", "converter", "etw-parser", "telemetry"])
    add("relog.exe", "etw_performance_tracing", "16. ETW / PERFORMANCE / TRACING", "Фильтрация, конвертация и сэмплирование логов счетчиков производительности BLG/CSV.", "READ_WRITE", "STANDARD", "SAFE", "OBSERVE", "CLI", monitor=True, templates=["relog.exe input.blg -f CSV -o output.csv"], tags=["relog", "blg", "csv", "perf-counters"])
    add("wpr.exe", "etw_performance_tracing", "16. ETW / PERFORMANCE / TRACING", "Windows Performance Recorder для записи сценариев ETW на уровне ядра и приложений.", "READ_WRITE", "ADMINISTRATOR", "LOW", "DIAGNOSE", "ETW", etw="Kernel Logger", modify=True, monitor=True, etw_pipe=True, subcommands={"-status": "Статус записи", "-start": "Запуск профиля трассировки", "-stop": "Сохранение ETL файла", "-cancel": "Отмена трассировки"}, templates=["wpr.exe -status", "wpr.exe -start GeneralProfile", "wpr.exe -stop trace.etl"], tags=["wpr", "etw", "wpt", "kernel-trace", "telemetry"])
    add("wpa.exe", "etw_performance_tracing", "16. ETW / PERFORMANCE / TRACING", "Графический анализатор Windows Performance Analyzer для глубокого разбора .ETL трассировок.", "READ", "STANDARD", "SAFE", "OBSERVE", "GUI_MMC_CPL", gui=True, monitor=True, templates=["wpa.exe \"{trace_etl}\""], tags=["gui", "wpa", "wpt", "etl-analysis", "profiling"])
    add("xperf.exe", "etw_performance_tracing", "16. ETW / PERFORMANCE / TRACING", "Консольный контроллер ETW трейсов из комплекта Windows Performance Toolkit (WPT).", "READ_WRITE", "ADMINISTRATOR", "MEDIUM", "DIAGNOSE", "ETW", modify=True, monitor=True, etw_pipe=True, templates=["xperf.exe -on latency", "xperf.exe -d trace.etl"], tags=["xperf", "adk", "etw", "latency", "dpc-isr"])

    # 17-23. NETWORK & DIAGNOSTICS
    add("ipconfig.exe", "network_basic", "17. NETWORK — BASIC", "Отображение сетевой конфигурации TCP/IP, шлюзов, DNS и сброс DNS кэша.", "READ_WRITE", "STANDARD", "LOW", "OBSERVE", "WIN32_API", ps="Get-NetIPConfiguration / Clear-DnsClientCache", win32="GetAdaptersAddresses", monitor=True, templates=["ipconfig.exe /all", "ipconfig.exe /flushdns", "ipconfig.exe /renew"], tags=["network", "ipconfig", "dns", "dhcp"])
    add("netstat.exe", "network_basic", "17. NETWORK — BASIC", "Активные TCP соединения, прослушиваемые порты, статистика протоколов и PID процессов.", "READ", "STANDARD", "SAFE", "OBSERVE", "WIN32_API", ps="Get-NetTCPConnection / Get-NetUDPEndpoint", win32="GetExtendedTcpTable / GetExtendedUdpTable", monitor=True, templates=["netstat.exe -ano", "netstat.exe -r", "netstat.exe -e"], tags=["network", "netstat", "ports", "connections", "telemetry"])
    add("ping.exe", "network_basic", "17. NETWORK — BASIC", "Проверка сетевой доступности узла и задержки RTT по протоколу ICMP.", "READ", "STANDARD", "SAFE", "DIAGNOSE", "WIN32_API", ps="Test-Connection", win32="IcmpSendEcho", monitor=True, templates=["ping.exe -n 4 {host}"], tags=["ping", "icmp", "latency"])
    add("tracert.exe", "network_basic", "17. NETWORK — BASIC", "Трассировка маршрута IP пакетов к удаленному узлу по сетевым хопам.", "READ", "STANDARD", "SAFE", "DIAGNOSE", "WIN32_API", ps="Test-NetConnection -TraceRoute", monitor=True, templates=["tracert.exe -d {host}"], tags=["traceroute", "network", "hops"])
    add("pathping.exe", "network_diagnostics", "19. NETWORK DIAGNOSTICS", "Комплексный анализ сетевого маршрута с вычислением потерь пакетов на узлах.", "READ", "STANDARD", "SAFE", "DIAGNOSE", "WIN32_API", monitor=True, templates=["pathping.exe -n {host}"], tags=["pathping", "loss", "packet-loss"])
    add("pktmon.exe", "network_diagnostics", "19. NETWORK DIAGNOSTICS", "Встроенный высокопроизводительный сниффер пакетов и сетевой монитор Windows (Packet Monitor).", "READ_WRITE", "ADMINISTRATOR", "MEDIUM", "DIAGNOSE", "ETW", ps="Get-NetEventSession", etw="Microsoft-Windows-PktMon", modify=True, monitor=True, etw_pipe=True, subcommands={"start": "Запуск захвата пакетов", "stop": "Остановка сниффера", "status": "Статус активности", "filter add": "Добавление фильтра IP/порта", "counters": "Счетчики трафика по интерфейсам", "pcapng": "Преобразование лога в формат Wireshark PCAPNG", "etl2txt": "Конвертация в текст"}, templates=["pktmon.exe start --etw", "pktmon.exe counters", "pktmon.exe stop", "pktmon.exe pcapng pktmon.etl -o out.pcapng"], tags=["pktmon", "packet-capture", "sniffer", "pcap", "network-telemetry"])
    add("netsh.exe", "network_netsh", "18. NETWORK — NETSH", "Универсальный сетевой конфигуратор (AdvFirewall, WLAN, WinHTTP, IPsec, Routing, Interface, Trace).", "READ_WRITE", "ADMINISTRATOR", "CRITICAL", "ADMIN", "CLI", ps="NetTCPIP / NetSecurity / NetAdapter modules", win32="INetFwPolicy2 / iphlpapi.dll", modify=True, monitor=True, etw_pipe=True, subcommands={"advfirewall": "Брандмауэр Windows", "wlan": "Wi-Fi профили и сети", "interface": "Сетевые адаптеры и IP", "winhttp": "Прокси HTTP", "trace": "Сетевой сниффер ETW", "dnsclient": "Настройки DNS"}, sub_tree={"advfirewall": ["show allprofiles", "set allprofiles state on/off", "firewall add rule", "firewall show rule"], "wlan": ["show interfaces", "show networks", "show profiles", "export profile"], "interface": ["ip show config", "ip set address", "ip reset", "ipv6 show address"], "winhttp": ["show proxy", "set proxy", "reset proxy"], "trace": ["start capture=yes", "stop", "show status"]}, templates=["netsh.exe advfirewall show allprofiles", "netsh.exe wlan show interfaces", "netsh.exe winhttp show proxy"], tags=["netsh", "firewall", "wlan", "proxy", "network-core"])
    add("route.exe", "tcpip_routing", "22. TCP/IP / ROUTING", "Просмотр и модификация таблиц сетевой маршрутизации IP.", "READ_WRITE", "ADMINISTRATOR", "HIGH", "ADMIN", "WIN32_API", ps="Get-NetRoute / New-NetRoute", win32="GetIpForwardTable2", modify=True, templates=["route.exe print", "route.exe add {net} mask {mask} {gw}"], tags=["routing", "gateway", "network"])
    add("arp.exe", "tcpip_routing", "22. TCP/IP / ROUTING", "Отображение и редактирование кэша сопоставления IP-адресов с MAC-адресами.", "READ_WRITE", "STANDARD", "LOW", "OBSERVE", "WIN32_API", win32="GetIpNetTable", monitor=True, templates=["arp.exe -a", "arp.exe -d *"], tags=["arp", "mac", "network"])
    add("getmac.exe", "network_basic", "17. NETWORK — BASIC", "Получение физических MAC-адресов сетевых плат хоста.", "READ", "STANDARD", "SAFE", "OBSERVE", "WIN32_API", win32="GetAdaptersInfo", monitor=True, templates=["getmac.exe /fo csv /v"], tags=["mac", "hardware", "adapter"])
    add("nslookup.exe", "dns", "21. DNS", "Запросы к серверам доменных имен DNS для резолвинга записей A, MX, TXT, CNAME, PTR.", "READ", "STANDARD", "SAFE", "OBSERVE", "WIN32_API", ps="Resolve-DnsName", win32="DnsQuery_W", monitor=True, templates=["nslookup.exe {host}", "nslookup.exe -type=MX {domain}"], tags=["dns", "nslookup", "resolver"])
    add("hostname.exe", "network_basic", "17. NETWORK — BASIC", "Отображение сетевого имени локального компьютера.", "READ", "STANDARD", "SAFE", "OBSERVE", "WIN32_API", win32="GetComputerNameExW", monitor=True, templates=["hostname.exe"], tags=["hostname", "identity"])
    add("nbtstat.exe", "network_basic", "17. NETWORK — BASIC", "Диагностика протокола NetBIOS поверх TCP/IP и кэша имен.", "READ", "STANDARD", "SAFE", "OBSERVE", "WIN32_API", monitor=True, templates=["nbtstat.exe -c", "nbtstat.exe -n"], tags=["netbios", "nbt", "smb"])

    # 13. SECURITY / ACCESS CONTROL & 14. GROUP POLICY
    add("whoami.exe", "security_access_control", "13. SECURITY / ACCESS CONTROL", "Отображение контекста безопасности: пользователь, SID, группы, привилегии и UAC Integrity Level.", "READ", "STANDARD", "SAFE", "OBSERVE", "WIN32_API", ps="[System.Security.Principal.WindowsIdentity]::GetCurrent()", win32="GetTokenInformation", monitor=True, subcommands={"/all": "Полный дамп контекста", "/priv": "Только привилегии", "/groups": "Группы и SID", "/user": "Текущий пользователь"}, templates=["whoami.exe /all", "whoami.exe /priv", "whoami.exe /groups"], tags=["whoami", "security", "token", "privileges", "uac"])
    add("runas.exe", "security_access_control", "13. SECURITY / ACCESS CONTROL", "Запуск процесса от имени другой учетной записи пользователя.", "WRITE", "STANDARD", "HIGH", "CONTROL", "WIN32_API", ps="Start-Process -Credential", win32="CreateProcessWithLogonW", unattended=False, modify=True, templates=["runas.exe /user:{user} \"{cmd}\""], tags=["runas", "privilege-escalation"])
    add("klist.exe", "security_access_control", "13. SECURITY / ACCESS CONTROL", "Просмотр, кэширование и очистка билетов аутентификации Kerberos (TGT / TGS).", "READ_WRITE", "STANDARD", "LOW", "OBSERVE", "WIN32_API", win32="LsaCallAuthenticationPackage", modify=True, monitor=True, templates=["klist.exe", "klist.exe purge"], tags=["kerberos", "tickets", "auth"])
    add("cmdkey.exe", "credentials", "40. CREDENTIALS", "Создание, отображение и удаление сохраненных учетных данных Windows Credential Manager.", "READ_WRITE", "STANDARD", "HIGH", "CONTROL", "WIN32_API", win32="CredEnumerateW / CredWriteW", modify=True, monitor=True, templates=["cmdkey.exe /list", "cmdkey.exe /delete:{target}"], tags=["cmdkey", "credentials", "vault"])
    add("gpresult.exe", "group_policy", "14. GROUP POLICY", "Анализ результирующей политики групповых политик GPO (Resultant Set of Policy / RSoP).", "READ", "STANDARD", "SAFE", "OBSERVE", "WMI_CIM", wmi="Root\\RSOP", monitor=True, templates=["gpresult.exe /r", "gpresult.exe /h gpreport.html /f"], tags=["gpo", "gpresult", "rsop", "policy"])
    add("gpupdate.exe", "group_policy", "14. GROUP POLICY", "Принудительное обновление настроек групповых политик GPO компьютера и пользователя.", "WRITE", "STANDARD", "MEDIUM", "CONTROL", "WIN32_API", ps="Invoke-GPUpdate -Force", win32="RefreshPolicyEx", modify=True, templates=["gpupdate.exe /force"], tags=["gpo", "gpupdate", "policy"])
    add("auditpol.exe", "security_access_control", "13. SECURITY / ACCESS CONTROL", "Просмотр и настройка политик аудита безопасности Windows Security Log.", "READ_WRITE", "ADMINISTRATOR", "HIGH", "ADMIN", "WIN32_API", ps="Get-AuditPolicy / Set-AuditPolicy", win32="AuditQuerySystemPolicy / AuditSetSystemPolicy", modify=True, monitor=True, subcommands={"/get /category:*": "Все категории аудита", "/set": "Включение/отключение аудита событий"}, templates=["auditpol.exe /get /category:*", "auditpol.exe /set /subcategory:\"Logon\" /success:enable /failure:enable"], tags=["audit", "auditpol", "security-log", "siem"])
    add("secedit.exe", "security_access_control", "13. SECURITY / ACCESS CONTROL", "Анализ и применение локальных шаблонов безопасности (Security Templates / Security DB).", "READ_WRITE", "ADMINISTRATOR", "CRITICAL", "ADMIN", "WIN32_API", modify=True, templates=["secedit.exe /analyze /db secedit.sdb /cfg {template}", "secedit.exe /configure /db secedit.sdb /cfg {template}"], tags=["secedit", "security-template", "hardening"])

    # 15. EVENT LOG & 51. WER
    add("wevtutil.exe", "event_log", "15. EVENT LOG", "Управление журналами событий Windows Event Log (чтение по XPath, экспорт, очистка, манифесты).", "READ_WRITE", "STANDARD", "MEDIUM", "OBSERVE", "WIN32_API", ps="Get-WinEvent / Clear-EventLog", win32="EvtQuery / EvtSubscribe", evtx="All Channels", modify=True, monitor=True, subcommands={"qe": "Запрос событий по XPath", "el": "Список каналов логов", "cl": "Очистка журнала событий", "gl": "Конфигурация канала"}, templates=["wevtutil.exe qe System /c:20 /rd:true /f:RenderedXml", "wevtutil.exe el", "wevtutil.exe cl {log_name}"], tags=["eventlog", "evtx", "wevtutil", "telemetry"])
    add("eventcreate.exe", "event_log", "15. EVENT LOG", "Запись пользовательского события с заданным ID и типом в журнал Application.", "WRITE", "STANDARD", "LOW", "CONTROL", "WIN32_API", win32="ReportEventW", modify=True, templates=["eventcreate.exe /T INFORMATION /ID 100 /L Application /D \"{msg}\""], tags=["eventcreate", "log-writer"])
    add("wecutil.exe", "event_log", "15. EVENT LOG", "Управление подписками на пересылку событий Windows Event Collector (WEC).", "READ_WRITE", "ADMINISTRATOR", "MEDIUM", "CONTROL", "WIN32_API", modify=True, monitor=True, templates=["wecutil.exe es", "wecutil.exe gs {sub}"], tags=["wec", "event-forwarding", "siem"])

    # 28. SERVICING & 30. BOOT & 61. RECOVERY
    add("dism.exe", "windows_servicing", "28. WINDOWS COMPONENTS / SERVICING", "Управление образами Windows, хранилищем компонентов WinSxS, пакетами обновлений и драйверами.", "READ_WRITE", "ADMINISTRATOR", "CRITICAL", "ADMIN", "WIN32_API", ps="Get-WindowsOptionalFeature / Repair-WindowsImage / Enable-WindowsOptionalFeature", win32="DismInitialize / DismOpenSession", modify=True, subcommands={"/Online /Cleanup-Image /CheckHealth": "Проверка флага повреждения", "/Online /Cleanup-Image /ScanHealth": "Глубокое сканирование хранилища", "/Online /Cleanup-Image /RestoreHealth": "Восстановление образа Windows", "/Online /Get-Features": "Список компонентов Windows", "/Online /Cleanup-Image /StartComponentCleanup": "Очистка устаревших версий WinSxS"}, templates=["dism.exe /Online /Cleanup-Image /ScanHealth", "dism.exe /Online /Cleanup-Image /RestoreHealth", "dism.exe /Online /Get-Features /Format:Table"], tags=["dism", "winsxs", "servicing", "windows-image", "repair"])
    add("sfc.exe", "windows_servicing", "28. WINDOWS COMPONENTS / SERVICING", "Проверка целостности и восстановление защищенных системных файлов Windows Resource Protection (WRP).", "READ_WRITE", "ADMINISTRATOR", "HIGH", "RECOVERY", "WIN32_API", ps="Repair-WindowsImage", win32="sfc.dll", modify=True, subcommands={"/scannow": "Проверка и исправление", "/verifyonly": "Только проверка без изменений"}, templates=["sfc.exe /scannow", "sfc.exe /verifyonly"], tags=["sfc", "wrp", "integrity", "system-files", "repair"])
    add("bcdedit.exe", "boot", "30. BOOT", "Управление хранилищем данных конфигурации загрузки Windows Boot Configuration Data (BCD).", "READ_WRITE", "ADMINISTRATOR", "CRITICAL", "DESTRUCTIVE", "WMI_CIM", ps="Get-CimInstance -Namespace root/wmi -ClassName BcdObject", wmi="Root\\WMI:BcdObject", modify=True, subcommands={"/enum all": "Все записи BCD", "/timeout": "Таймаут меню загрузки", "/set": "Установка параметров"}, templates=["bcdedit.exe /enum all", "bcdedit.exe /timeout 5", "bcdedit.exe /set {current} safeboot minimal"], tags=["bcd", "boot", "uefi", "safemode"])
    add("bcdboot.exe", "boot", "30. BOOT", "Инициализация и восстановление загрузочных файлов операционной системы на системный раздел EFI / BIOS.", "WRITE", "ADMINISTRATOR", "CRITICAL", "RECOVERY", "WIN32_API", modify=True, templates=["bcdboot.exe {win_dir} /s {efi_drive}: /f ALL"], tags=["bcdboot", "efi", "uefi-repair", "bootloader"])
    add("bootrec.exe", "boot", "30. BOOT", "Восстановление главной загрузочной записи MBR, загрузочного сектора и перестроение BCD (WinRE).", "WRITE", "ADMINISTRATOR", "CRITICAL", "RECOVERY", "WIN32_API", modify=True, templates=["bootrec.exe /fixmbr", "bootrec.exe /fixboot", "bootrec.exe /rebuildbcd"], tags=["mbr", "bootrec", "recovery", "boot-repair"])
    add("bootsect.exe", "boot", "30. BOOT", "Обновление главного загрузочного кода для разделов диска BOOTMGR/NTLDR.", "WRITE", "ADMINISTRATOR", "CRITICAL", "RECOVERY", "WIN32_API", modify=True, templates=["bootsect.exe /nt60 {drive}: /mbr"], tags=["bootsect", "bootmgr", "mbr"])
    add("reagentc.exe", "winre_recovery", "61. WINDOWS RECOVERY ENVIRONMENT", "Настройка и диагностика среды аварийного восстановления Windows Recovery Environment (WinRE).", "READ_WRITE", "ADMINISTRATOR", "HIGH", "RECOVERY", "WIN32_API", ps="Get-WinRE / Set-WinRE", modify=True, monitor=True, subcommands={"/info": "Статус среды WinRE", "/enable": "Включение WinRE", "/disable": "Отключение WinRE"}, templates=["reagentc.exe /info", "reagentc.exe /enable"], tags=["winre", "recovery", "reagentc", "boot"])

    # 35. SYSTEM INFORMATION & 37. BENCHMARK
    add("systeminfo.exe", "system_information", "35. SYSTEM INFORMATION", "Сводная системная информация: сборка ОС, BIOS, ОЗУ, хотфиксы, сетевые карты и Hyper-V.", "READ", "STANDARD", "SAFE", "OBSERVE", "WMI_CIM", ps="Get-ComputerInfo", wmi="Win32_OperatingSystem / Win32_ComputerSystem", monitor=True, templates=["systeminfo.exe /FO CSV"], tags=["systeminfo", "hardware", "os", "hotfix"])
    add("msinfo32.exe", "system_information", "35. SYSTEM INFORMATION", "Сведения о системе Microsoft System Information (GUI / NFO экспорт).", "READ", "STANDARD", "SAFE", "OBSERVE", "GUI_MMC_CPL", gui=True, monitor=True, templates=["msinfo32.exe /nfo report.nfo", "msinfo32.exe /report report.txt"], tags=["msinfo32", "hardware-report", "system-info"])
    add("winver.exe", "system_information", "35. SYSTEM INFORMATION", "Окно отображения версии, номера сборки и лицензиата Windows.", "READ", "STANDARD", "SAFE", "OBSERVE", "GUI_MMC_CPL", gui=True, templates=["winver.exe"], tags=["winver", "build", "gui"])
    add("winsat.exe", "benchmark_winsat", "37. WINDOWS EXPERIENCE / BENCHMARK", "Оценка производительности Windows System Assessment Tool (CPU, GPU, RAM, Disk).", "READ_WRITE", "ADMINISTRATOR", "LOW", "DIAGNOSE", "WMI_CIM", wmi="Win32_WinSAT", monitor=True, subcommands={"formal": "Полная оценка всех подсистем", "cpu": "Бенчмарк процессора", "mem": "Бенчмарк памяти", "disk": "Бенчмарк дисков"}, templates=["winsat.exe formal", "winsat.exe disk -drive c", "winsat.exe cpu -encryption"], tags=["winsat", "benchmark", "performance", "score"])
    add("tzutil.exe", "time_locale", "38. TIME / LOCALE", "Утилита командной строки для просмотра и смены часового пояса Windows (Time Zone Utility).", "READ_WRITE", "ADMINISTRATOR", "LOW", "CONTROL", "WIN32_API", ps="Get-TimeZone / Set-TimeZone", win32="GetTimeZoneInformation / SetTimeZoneInformation", modify=True, monitor=True, templates=["tzutil.exe /g", "tzutil.exe /l", "tzutil.exe /s \"{timezone_id}\""], tags=["timezone", "time", "clock"])
    add("tpmtool.exe", "tpm", "41. TPM", "Диагностика модуля доверенной платформы Trusted Platform Module (TPM 2.0).", "READ", "ADMINISTRATOR", "SAFE", "OBSERVE", "WMI_CIM", ps="Get-Tpm", wmi="Win32_Tpm", monitor=True, subcommands={"getdeviceinformation": "Информация о чипе TPM", "gatherlogs": "Сбор логов TPM"}, templates=["tpmtool.exe getdeviceinformation"], tags=["tpm", "tpm2", "security-hardware", "crypto"])
    add("bitsadmin.exe", "bits", "49. BITS", "Управление фоновой службой интеллектуальной передачи Background Intelligent Transfer Service (BITS).", "READ_WRITE", "STANDARD", "MEDIUM", "CONTROL", "COM", ps="Get-BitsTransfer / Start-BitsTransfer", com="IBackgroundCopyManager", modify=True, monitor=True, subcommands={"/list": "Список активных заданий BITS", "/create": "Создание задания", "/addfile": "Добавление URL", "/resume": "Возобновление"}, templates=["bitsadmin.exe /list /allusers", "bitsadmin.exe /create myJob", "bitsadmin.exe /addfile myJob {url} {local_path}"], tags=["bits", "download", "transfer", "background"])
    add("sxstrace.exe", "side_by_side_sxstrace", "52. SIDE-BY-SIDE / APPLICATION DIAGNOSTICS", "Диагностика сбоев загрузки манифестов и библиотек Side-by-Side (WinSxS / C++ Runtime / MFC).", "READ_WRITE", "ADMINISTRATOR", "LOW", "DIAGNOSE", "ETW", etw="Microsoft-Windows-Sxs", modify=True, monitor=True, subcommands={"Trace": "Запуск трассировки SxS", "Parse": "Преобразование бинарного лога в текстовый"}, templates=["sxstrace.exe Trace -logfile:sxs.etl", "sxstrace.exe Parse -logfile:sxs.etl -outfile:sxs.txt"], tags=["sxstrace", "side-by-side", "dll-hell", "manifest-diagnostics"])

    # 08. SERVICES & 10. REGISTRY
    add("sc.exe", "services", "08. SERVICES", "Командный интерфейс диспетчера служебных процессов Windows Service Control Manager (SCM).", "READ_WRITE", "ADMINISTRATOR", "HIGH", "CONTROL", "WIN32_API", ps="Get-Service / Start-Service / Stop-Service / Set-Service", wmi="Win32_Service", win32="OpenSCManagerW / ControlService", modify=True, monitor=True, subcommands={"query": "Список служб", "queryex": "Службы с PID", "qc": "Конфигурация службы", "start": "Запуск", "stop": "Остановка", "config": "Смена типа запуска"}, templates=["sc.exe query type= service state= all", "sc.exe queryex {service}", "sc.exe qc {service}", "sc.exe start {service}", "sc.exe stop {service}"], tags=["services", "scm", "daemon", "sc"])
    add("reg.exe", "registry", "10. REGISTRY", "Консольный интерфейс REST/CRUD к системному реестру Windows (HKLM, HKCU, HKCR, HKU, HKCC).", "READ_WRITE", "STANDARD", "HIGH", "CONTROL", "REGISTRY", ps="Get-ItemProperty / Set-ItemProperty", wmi="StdRegProv", win32="RegOpenKeyExW / RegQueryValueExW", modify=True, monitor=True, subcommands={"query": "Чтение ключа", "add": "Запись параметра", "delete": "Удаление", "export": "Экспорт в .reg", "import": "Импорт", "save": "Сохранение куста Hive", "load": "Монтирование куста"}, templates=["reg.exe query \"{key}\" /v {value}", "reg.exe add \"{key}\" /v {value} /t {type} /d {data} /f", "reg.exe delete \"{key}\" /v {value} /f"], tags=["registry", "reg", "hive", "config"])
    add("regedit.exe", "registry", "10. REGISTRY", "Графический редактор системного реестра Windows Registry Editor.", "READ_WRITE", "ADMINISTRATOR", "HIGH", "CONTROL", "GUI_MMC_CPL", gui=True, modify=True, templates=["regedit.exe", "regedit.exe /s \"{reg_file}\""], tags=["gui", "regedit", "registry"])
    add("regini.exe", "registry", "10. REGISTRY", "Пакетное изменение разрешений ACL на ветки реестра из конфигурационных файлов.", "WRITE", "ADMINISTRATOR", "CRITICAL", "ADMIN", "WIN32_API", win32="RegSetKeySecurity", modify=True, templates=["regini.exe \"{script_ini}\""], tags=["regini", "registry-acl", "permissions"])

    # 12. USERS / GROUPS / SESSIONS & 25. REMOTE
    add("net.exe", "users_groups_sessions", "12. USERS / GROUPS / SESSIONS", "Управление учетными записями пользователей, локальными группами, службами и сетевыми шарами.", "READ_WRITE", "ADMINISTRATOR", "HIGH", "CONTROL", "WIN32_API", ps="Get-LocalUser / New-LocalUser / Get-SmbShare", win32="NetUserEnum / NetLocalGroupEnum / NetShareEnum", modify=True, monitor=True, subcommands={"user": "Управление пользователями", "localgroup": "Локальные группы", "start": "Запуск службы", "share": "Сетевые папки"}, templates=["net.exe user", "net.exe localgroup Administrators", "net.exe start"], tags=["net", "users", "groups", "shares"])
    add("net1.exe", "users_groups_sessions", "12. USERS / GROUPS / SESSIONS", "Внутренний исполнительный бинарник net.exe для сетевых и пользовательских операций.", "READ_WRITE", "ADMINISTRATOR", "HIGH", "CONTROL", "WIN32_API", modify=True, templates=["net1.exe user"], tags=["net1", "users"])
    add("quser.exe", "users_groups_sessions", "12. USERS / GROUPS / SESSIONS", "Отображение информации о пользователях, вошедших в систему локально или по RDP.", "READ", "STANDARD", "SAFE", "OBSERVE", "WIN32_API", win32="WTSEnumerateSessionsW", monitor=True, templates=["quser.exe"], tags=["quser", "sessions", "rdp"])
    add("qwinsta.exe", "users_groups_sessions", "12. USERS / GROUPS / SESSIONS", "Отображение состояния сеансов оконных станций терминального сервера (Query WinStation).", "READ", "STANDARD", "SAFE", "OBSERVE", "WIN32_API", win32="WTSEnumerateSessionsW", monitor=True, templates=["qwinsta.exe"], tags=["qwinsta", "winstation", "rdp"])
    add("logoff.exe", "shutdown_session_control", "66. SHUTDOWN / SESSION CONTROL", "Завершение активного сеанса пользователя или сессии удаленного рабочего стола.", "WRITE", "STANDARD", "MEDIUM", "CONTROL", "WIN32_API", win32="WTSDisconnectSession / ExitWindowsEx", modify=True, templates=["logoff.exe", "logoff.exe {session_id}"], tags=["logoff", "session", "user"])
    add("shutdown.exe", "shutdown_session_control", "66. SHUTDOWN / SESSION CONTROL", "Управление питанием: выключение, перезагрузка, отмена таймера или гибернация хоста.", "WRITE", "ADMINISTRATOR", "HIGH", "ADMIN", "WIN32_API", ps="Stop-Computer / Restart-Computer", win32="InitiateSystemShutdownExW / ExitWindowsEx", modify=True, subcommands={"/s": "Выключение", "/r": "Перезагрузка", "/a": "Отмена", "/h": "Гибернация"}, templates=["shutdown.exe /s /t 0", "shutdown.exe /r /t 0", "shutdown.exe /a"], tags=["power", "shutdown", "reboot"])
    add("mstsc.exe", "rdp", "26. RDP", "Клиент подключения к удаленному рабочему столу Microsoft Remote Desktop Connection.", "READ_WRITE", "STANDARD", "SAFE", "CONTROL", "GUI_MMC_CPL", gui=True, templates=["mstsc.exe /v:{server}", "mstsc.exe /admin"], tags=["rdp", "mstsc", "remote-desktop"])
    add("winrs.exe", "remote_management", "25. REMOTE MANAGEMENT", "Клиент удаленного выполнения команд Windows Remote Shell (WinRM).", "READ_WRITE", "STANDARD", "HIGH", "CONTROL", "CLI", ps="Enter-PSSession / Invoke-Command", modify=True, templates=["winrs.exe -r:{server} \"{cmd}\""], tags=["winrs", "winrm", "remoting"])
    add("msiexec.exe", "windows_installer", "27. WINDOWS INSTALLER", "Установщик Windows Installer для развертывания, обновления и удаления пакетов MSI / MSP.", "READ_WRITE", "ADMINISTRATOR", "HIGH", "CONTROL", "WIN32_API", win32="MsiInstallProductW", modify=True, templates=["msiexec.exe /i \"{msi_file}\" /qn /norestart", "msiexec.exe /x \"{msi_file}\" /qn"], tags=["msi", "installer", "software"])

    # 56. WINDOWS DEFENDER / SECURITY
    add("mpcmdrun.exe", "defender_security", "56. WINDOWS DEFENDER / SECURITY", "Командная строка антивируса Microsoft Defender Antivirus (сканирование, сигнатуры, карантин).", "READ_WRITE", "ADMINISTRATOR", "HIGH", "DIAGNOSE", "CLI", ps="Get-MpPreference / Start-MpScan / Update-MpSignature", wmi="Root\\Microsoft\\Windows\\Defender", modify=True, monitor=True, subcommands={"-Scan -ScanType 1": "Быстрое сканирование", "-Scan -ScanType 2": "Полное сканирование", "-SignatureUpdate": "Обновление баз", "-GetFiles": "Диагностический лог"}, templates=["MpCmdRun.exe -SignatureUpdate", "MpCmdRun.exe -Scan -ScanType 1"], tags=["defender", "antivirus", "security", "mpcmdrun"])

    # 65. MMC MANAGEMENT CONSOLES (.msc)
    msc_consoles = [
        ("compmgmt.msc", "65. MMC MANAGEMENT CONSOLES", "Оснастка: Управление компьютером (Computer Management).", "ADMINISTRATOR", "LOW", "mmc.exe compmgmt.msc"),
        ("devmgmt.msc", "65. MMC MANAGEMENT CONSOLES", "Оснастка: Диспетчер устройств (Device Manager).", "ADMINISTRATOR", "LOW", "mmc.exe devmgmt.msc"),
        ("diskmgmt.msc", "65. MMC MANAGEMENT CONSOLES", "Оснастка: Управление дисками (Disk Management).", "ADMINISTRATOR", "MEDIUM", "mmc.exe diskmgmt.msc"),
        ("eventvwr.msc", "65. MMC MANAGEMENT CONSOLES", "Оснастка: Просмотр событий (Event Viewer).", "STANDARD", "SAFE", "mmc.exe eventvwr.msc"),
        ("fsmgmt.msc", "65. MMC MANAGEMENT CONSOLES", "Оснастка: Общие папки и сессии SMB (Shared Folders).", "ADMINISTRATOR", "LOW", "mmc.exe fsmgmt.msc"),
        ("gpedit.msc", "65. MMC MANAGEMENT CONSOLES", "Оснастка: Редактор локальной групповой политики (Group Policy Editor).", "ADMINISTRATOR", "HIGH", "mmc.exe gpedit.msc"),
        ("lusrmgr.msc", "65. MMC MANAGEMENT CONSOLES", "Оснастка: Локальные пользователи и группы (Local Users and Groups).", "ADMINISTRATOR", "MEDIUM", "mmc.exe lusrmgr.msc"),
        ("perfmon.msc", "65. MMC MANAGEMENT CONSOLES", "Оснастка: Системный монитор производительности (Performance Monitor).", "STANDARD", "SAFE", "mmc.exe perfmon.msc"),
        ("services.msc", "65. MMC MANAGEMENT CONSOLES", "Оснастка: Диспетчер служб Windows (Services).", "ADMINISTRATOR", "MEDIUM", "mmc.exe services.msc"),
        ("taskschd.msc", "65. MMC MANAGEMENT CONSOLES", "Оснастка: Планировщик заданий (Task Scheduler).", "STANDARD", "LOW", "mmc.exe taskschd.msc"),
        ("wf.msc", "65. MMC MANAGEMENT CONSOLES", "Оснастка: Брандмауэр Защитника Windows в режиме повышенной безопасности (Firewall).", "ADMINISTRATOR", "MEDIUM", "mmc.exe wf.msc"),
        ("certmgr.msc", "65. MMC MANAGEMENT CONSOLES", "Оснастка: Сертификаты текущего пользователя (Certificates).", "STANDARD", "LOW", "mmc.exe certmgr.msc"),
        ("wmimgmt.msc", "65. MMC MANAGEMENT CONSOLES", "Оснастка: Элемент управления WMI (WMI Control).", "ADMINISTRATOR", "MEDIUM", "mmc.exe wmimgmt.msc"),
        ("printmanagement.msc", "65. MMC MANAGEMENT CONSOLES", "Оснастка: Управление печатью (Print Management).", "ADMINISTRATOR", "LOW", "mmc.exe printmanagement.msc")
    ]
    for msc_name, code, purpose, priv, danger, cmd in msc_consoles:
        add(msc_name, "mmc_management_msc", code, purpose, "READ_WRITE", priv, danger, "CONTROL" if priv == "ADMINISTRATOR" else "OBSERVE", "GUI_MMC_CPL", com="MMC20.Application", gui=True, msc=True, unattended=False, templates=[cmd], tags=["gui", "msc", "mmc", "admin-console"])

    # 64. CONTROL PANEL (.cpl)
    cpl_applets = [
        ("appwiz.cpl", "Программы и компоненты (Установка и удаление программ)"),
        ("firewall.cpl", "Брандмауэр Защитника Windows"),
        ("hdwwiz.cpl", "Мастер установки оборудования"),
        ("ncpa.cpl", "Сетевые подключения (Network Connections)"),
        ("powercfg.cpl", "Электропитание (Power Options)"),
        ("sysdm.cpl", "Свойства системы (System Properties)"),
        ("timedate.cpl", "Дата и время (Date and Time)"),
        ("main.cpl", "Свойства мыши и клавиатуры"),
        ("mmsys.cpl", "Звуковые устройства (Sound Devices)"),
        ("desk.cpl", "Параметры экрана (Display Settings)"),
    ]
    for cpl_name, purpose in cpl_applets:
        add(cpl_name, "control_panel_cpl", "64. CONTROL PANEL", purpose, "READ_WRITE", "STANDARD", "LOW", "CONTROL", "GUI_MMC_CPL", gui=True, cpl=True, unattended=False, templates=[f"control.exe {cpl_name}"], tags=["gui", "cpl", "control-panel"])

    # 63. SYSTEM CONFIGURATION
    add("msconfig.exe", "system_configuration", "63. SYSTEM CONFIGURATION", "Конфигурация системы (System Configuration): выбор режима загрузки и диагностика.", "READ_WRITE", "ADMINISTRATOR", "MEDIUM", "CONTROL", "GUI_MMC_CPL", gui=True, unattended=False, modify=True, templates=["msconfig.exe"], tags=["gui", "boot", "config"])
    add("control.exe", "system_configuration", "63. SYSTEM CONFIGURATION", "Панель управления Windows (Control Panel).", "READ_WRITE", "STANDARD", "LOW", "CONTROL", "GUI_MMC_CPL", gui=True, unattended=False, templates=["control.exe", "control.exe /name Microsoft.System"], tags=["gui", "control-panel"])
    add("ms-settings:", "system_configuration", "63. SYSTEM CONFIGURATION", "URI протокол доступа к современным разделам параметров Windows 10/11 (Settings App).", "READ_WRITE", "STANDARD", "SAFE", "OBSERVE", "GUI_MMC_CPL", gui=True, unattended=False, templates=["start ms-settings:", "start ms-settings:windowsupdate", "start ms-settings:network"], tags=["settings", "uwp", "uri", "gui"])

    # 45. CMD BUILTINS
    cmd_builtins = [
        ("assoc", "Отображение или изменение сопоставлений расширений имен файлов."),
        ("chcp", "Просмотр или изменение активной кодовой страницы консоли (например, 65001 для UTF-8)."),
        ("cls", "Очистка экрана командной строки."),
        ("copy", "Копирование одного или нескольких файлов в другое место."),
        ("del", "Удаление одного или нескольких файлов."),
        ("dir", "Отображение списка файлов и подпапок в каталоге."),
        ("echo", "Вывод сообщений или включение/выключение режима отображения команд."),
        ("mkdir", "Создание нового каталога."),
        ("move", "Перемещение одного или нескольких файлов или каталогов."),
        ("path", "Отображение или установка пути поиска исполняемых файлов."),
        ("ren", "Переименование файла или файлов."),
        ("rmdir", "Удаление каталога (папки)."),
        ("set", "Отображение, установка или удаление переменных среды CMD."),
        ("start", "Запуск отдельного окна для выполнения указанной программы или команды."),
        ("subst", "Связывание пути файловой системы с буквой виртуального диска."),
        ("title", "Установка заголовка окна для окна командной строки."),
        ("type", "Отображение содержимого текстового файла."),
        ("ver", "Отображение версии операционной системы Windows."),
        ("vol", "Отображение метки тома диска и серийного номера."),
    ]
    for b_name, purpose in cmd_builtins:
        add(b_name, "cmd_builtins", "45. MS-DOS / CMD BUILTINS", purpose, "READ_WRITE", "STANDARD", "SAFE" if b_name in ["dir", "ver", "vol", "type", "path", "chcp"] else "MEDIUM", "OBSERVE" if b_name in ["dir", "ver", "vol", "type", "path", "chcp"] else "CONTROL", "CLI", builtin=True, templates=[f"cmd.exe /c {b_name}"], tags=["cmd", "builtin", "msdos"])

    DATA_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(DATA_PATH, 'w', encoding='utf-8') as f:
        json.dump({
            "version": "2.0.0",
            "total_items": len(items),
            "catalog": items
        }, f, indent=2, ensure_ascii=False)

    print(f"Успешно сохранен полный реестр: {len(items)} инструментов в {DATA_PATH}")

if __name__ == '__main__':
    build_catalog()
