# -*- coding: utf-8 -*-
# =============================================================================
# Process Name: Google Cloud Alert Engine and Incident Manager
# =============================================================================
# Description:
#   Evaluates log-based alert thresholds, monitors real-time incident state,
#   and manages alert policies for Google Cloud Platform workloads.
#
# Examples:
#   >>> from apps.gcloud_monitor.src.alert_engine import GCloudAlertEngine
#   >>> alert_engine = GCloudAlertEngine()
#   >>> incidents = alert_engine.get_active_incidents()
#
# File: alert_engine.py
# Project: ai-breadboard
# Package: apps.gcloud_monitor.src
# Class: GCloudAlertEngine
# Author: hypo69
# Copyright: © 2026 hypo69
# =============================================================================

"""Log-based alerts, threshold evaluation, and incident state tracking."""

from __future__ import annotations

import datetime
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional

from apps.gcloud_monitor.src.auth import GCloudAuthManager
from apps.gcloud_monitor.src.logging_service import GCloudLoggingService
from apps.gcloud_monitor.src.metrics_service import GCloudMetricsService
from logger import logger


@dataclass
class AlertPolicy:
    """Alert policy rule configuration."""

    policy_id: str = ''
    display_name: str = ''
    condition_type: str = 'log_match'
    filter_or_metric: str = ''
    threshold_value: float = 0.0
    duration_seconds: int = 300
    enabled: bool = True
    severity: str = 'WARNING'


@dataclass
class Incident:
    """An active or resolved incident generated by an alert trigger."""

    incident_id: str = ''
    policy_name: str = ''
    severity: str = 'WARNING'
    summary: str = ''
    started_at: str = ''
    ended_at: Optional[str] = None
    state: str = 'OPEN'
    observed_value: str = ''
    resource: str = ''

    def to_dict(self) -> Dict[str, Any]:
        """Convert incident dataclass to dictionary."""
        return asdict(self)


class GCloudAlertEngine:
    """Evaluates telemetry data against alert rules to flag incidents."""

    def __init__(
        self,
        auth_mgr: Optional[GCloudAuthManager] = None,
        metrics_svc: Optional[GCloudMetricsService] = None,
        logging_svc: Optional[GCloudLoggingService] = None,
    ) -> None:
        """Initialize Alert Engine.

        Args:
            auth_mgr (Optional[GCloudAuthManager]): Auth manager instance.
            metrics_svc (Optional[GCloudMetricsService]): Metrics service instance.
            logging_svc (Optional[GCloudLoggingService]): Logging service instance.
        """
        self.auth_mgr: GCloudAuthManager = auth_mgr if auth_mgr else GCloudAuthManager()
        self.metrics_svc: GCloudMetricsService = (
            metrics_svc if metrics_svc else GCloudMetricsService(auth_mgr=self.auth_mgr)
        )
        self.logging_svc: GCloudLoggingService = (
            logging_svc if logging_svc else GCloudLoggingService(auth_mgr=self.auth_mgr)
        )

        self.default_policies: List[AlertPolicy] = [
            AlertPolicy(
                policy_id='pol_err_rate',
                display_name='High Error Rate Alert',
                condition_type='metric_threshold',
                filter_or_metric='error_rate_percent',
                threshold_value=5.0,
                duration_seconds=300,
                severity='CRITICAL',
            ),
            AlertPolicy(
                policy_id='pol_p95_latency',
                display_name='P95 Latency Spike',
                condition_type='metric_threshold',
                filter_or_metric='p95_latency_ms',
                threshold_value=1200.0,
                duration_seconds=180,
                severity='WARNING',
            ),
            AlertPolicy(
                policy_id='pol_auth_failure',
                display_name='Frequent Authentication Errors',
                condition_type='log_match',
                filter_or_metric='textPayload:"AuthenticationError"',
                threshold_value=10.0,
                duration_seconds=300,
                severity='WARNING',
            ),
        ]

    def get_active_incidents(self) -> List[Incident]:
        """Evaluate policies and return active incidents.

        Returns:
            List[Incident]: Active system incidents.
        """
        now = datetime.datetime.now(datetime.timezone.utc)
        metrics = self.metrics_svc.get_metrics_summary()

        incidents: List[Incident] = []
        if metrics.error_rate_percent > 1.5:
            incidents.append(
                Incident(
                    incident_id='inc_88219',
                    policy_name='Elevated Error Rate Alert',
                    severity='WARNING',
                    summary=f'Error rate currently at {metrics.error_rate_percent}% (threshold 1.5%)',
                    started_at=(now - datetime.timedelta(minutes=8)).isoformat(),
                    state='OPEN',
                    observed_value=f'{metrics.error_rate_percent}%',
                    resource=f'projects/{metrics.project_id}',
                )
            )

        if metrics.p95_latency_ms > 500.0:
            incidents.append(
                Incident(
                    incident_id='inc_88220',
                    policy_name='P95 Latency Threshold',
                    severity='WARNING',
                    summary=f'P95 latency reached {metrics.p95_latency_ms}ms on API gateway',
                    started_at=(now - datetime.timedelta(minutes=3)).isoformat(),
                    state='OPEN',
                    observed_value=f'{metrics.p95_latency_ms}ms',
                    resource='service/api-gateway',
                )
            )

        return incidents
