# -*- coding: utf-8 -*-
# =============================================================================
# Process Name: AI-Breadboard Apps Windows - Window Management Constants
# =============================================================================
# Description:
#   Win32, DWM, Shell и Registry константы для подсистемы управления окнами.
#   Содержит коды действий SystemParametersInfoW, атрибуты DwmSetWindowAttribute,
#   системные цвета и флаги обновления параметров.
#
# Usage Examples:
#   Python API:
#     from apps.windows.modules.window_control_plane.constants import (
#         SPI_GETFOREGROUNDLOCKTIMEOUT, SPI_SETFOREGROUNDLOCKTIMEOUT, SPIF_SENDCHANGE
#     )
#
# File: constants.py
# Project: ai-breadboard
# Package: apps.windows.modules.window_control_plane
# Author: hypo69
# Copyright: © 2026 hypo69
# Updated: 2026-10-06 18:00:00
# =============================================================================

from __future__ import annotations
"""Константы Win32 API, DWM, Display и реестра для Window Management Control Plane."""

# -----------------------------------------------------------------------------
# Флаги уведомления системы при SystemParametersInfoW
# -----------------------------------------------------------------------------
SPIF_UPDATEINIFILE = 0x0001
SPIF_SENDCHANGE = 0x0002
SPIF_SENDWININICHANGE = 0x0002

# -----------------------------------------------------------------------------
# Focus / Foreground / Activation (Категория 1)
# -----------------------------------------------------------------------------
SPI_GETACTIVEWINDOWTRACKING = 0x1000
SPI_SETACTIVEWINDOWTRACKING = 0x1001
SPI_GETACTIVEWNDTRKTIMEOUT = 0x2002
SPI_SETACTIVEWNDTRKTIMEOUT = 0x2003
SPI_GETFOREGROUNDLOCKTIMEOUT = 0x2000
SPI_SETFOREGROUNDLOCKTIMEOUT = 0x2001
SPI_GETFOREGROUNDFLASHCOUNT = 0x2004
SPI_SETFOREGROUNDFLASHCOUNT = 0x2005
SPI_GETKEYBOARDCUES = 0x100A
SPI_SETKEYBOARDCUES = 0x100B
SPI_GETFOCUSBORDERWIDTH = 0x200E
SPI_SETFOCUSBORDERWIDTH = 0x200F
SPI_GETFOCUSBORDERHEIGHT = 0x2010
SPI_SETFOCUSBORDERHEIGHT = 0x2011

# -----------------------------------------------------------------------------
# Animations / Visual Effects (Категория 2)
# -----------------------------------------------------------------------------
SPI_GETANIMATION = 0x0048
SPI_SETANIMATION = 0x0049
SPI_GETMENUANIMATION = 0x1002
SPI_SETMENUANIMATION = 0x1003
SPI_GETMENUFADE = 0x1012
SPI_SETMENUFADE = 0x1013
SPI_GETTOOLTIPANIMATION = 0x1016
SPI_SETTOOLTIPANIMATION = 0x1017
SPI_GETTOOLTIPFADE = 0x1018
SPI_SETTOOLTIPFADE = 0x1019
SPI_GETCURSORSHADOW = 0x101A
SPI_SETCURSORSHADOW = 0x101B
SPI_GETCOMBOBOXANIMATION = 0x1004
SPI_SETCOMBOBOXANIMATION = 0x1005
SPI_GETLISTBOXSMOOTHSCROLLING = 0x1006
SPI_SETLISTBOXSMOOTHSCROLLING = 0x1007
SPI_GETSELECTIONFADE = 0x1014
SPI_SETSELECTIONFADE = 0x1015
SPI_GETUIEFFECTS = 0x103E
SPI_SETUIEFFECTS = 0x103F
SPI_GETCLIENTAREAANIMATION = 0x1042
SPI_SETCLIENTAREAANIMATION = 0x1043
SPI_GETDRAGFULLWINDOWS = 0x0026
SPI_SETDRAGFULLWINDOWS = 0x0025
SPI_GETFONTSMOOTHING = 0x004A
SPI_SETFONTSMOOTHING = 0x004B
SPI_GETCLEARTYPE = 0x1048
SPI_SETCLEARTYPE = 0x1049

# -----------------------------------------------------------------------------
# Window Geometry / Metrics (Категории 3 и 14)
# -----------------------------------------------------------------------------
SPI_GETBORDER = 0x0005
SPI_SETBORDER = 0x0006
SPI_GETNONCLIENTMETRICS = 0x0029
SPI_SETNONCLIENTMETRICS = 0x002A
SPI_GETICONMETRICS = 0x002D
SPI_SETICONMETRICS = 0x002E
SPI_GETICONTITLEWRAP = 0x0019
SPI_SETICONTITLEWRAP = 0x001A
SPI_GETDOUBLECLICKWIDTH = 0x001D
SPI_SETDOUBLECLICKWIDTH = 0x001D
SPI_GETDOUBLECLICKHEIGHT = 0x001E
SPI_SETDOUBLECLICKHEIGHT = 0x001E
SPI_GETDOUBLECLICKTIME = 0x001F
SPI_SETDOUBLECLICKTIME = 0x0020
SPI_GETMENUSHOWDELAY = 0x006A
SPI_SETMENUSHOWDELAY = 0x006B
SPI_GETICONSPACING = 0x0030
SPI_SETICONSPACING = 0x0031
SPI_GETCARETWIDTH = 0x2006
SPI_SETCARETWIDTH = 0x2007

# -----------------------------------------------------------------------------
# Mouse Behaviors (Категория 9)
# -----------------------------------------------------------------------------
SPI_GETMOUSESPEED = 0x0070
SPI_SETMOUSESPEED = 0x0071
SPI_GETMOUSE = 0x0003
SPI_SETMOUSE = 0x0004
SPI_GETMOUSEHOVERTIME = 0x0066
SPI_SETMOUSEHOVERTIME = 0x0067
SPI_GETMOUSEHOVERWIDTH = 0x0062
SPI_SETMOUSEHOVERWIDTH = 0x0063
SPI_GETMOUSEHOVERHEIGHT = 0x0064
SPI_SETMOUSEHOVERHEIGHT = 0x0065
SPI_GETMOUSEBUTTONSWAP = 0x0017
SPI_SETMOUSEBUTTONSWAP = 0x0021
SPI_GETMOUSETRAILS = 0x005E
SPI_SETMOUSETRAILS = 0x005F
SPI_GETMOUSESONAR = 0x101C
SPI_SETMOUSESONAR = 0x101D
SPI_GETMOUSEVANISH = 0x1020
SPI_SETMOUSEVANISH = 0x1021
SPI_GETSNAPTODEFBUTTON = 0x005F
SPI_SETSNAPTODEFBUTTON = 0x0060

# -----------------------------------------------------------------------------
# Keyboard / Focus (Категория 10)
# -----------------------------------------------------------------------------
SPI_GETKEYBOARDDELAY = 0x0016
SPI_SETKEYBOARDDELAY = 0x0017
SPI_GETKEYBOARDSPEED = 0x000A
SPI_SETKEYBOARDSPEED = 0x000B
SPI_GETCURSORBLINKRATE = 0x000E
SPI_SETCURSORBLINKRATE = 0x000F
SPI_GETKEYBOARDPREF = 0x0044
SPI_SETKEYBOARDPREF = 0x0045
SPI_GETSTICKYKEYS = 0x003A
SPI_SETSTICKYKEYS = 0x003B
SPI_GETFILTERKEYS = 0x0032
SPI_SETFILTERKEYS = 0x0033
SPI_GETTOGGLEKEYS = 0x0034
SPI_SETTOGGLEKEYS = 0x0035
SPI_GETMOUSEKEYS = 0x0036
SPI_SETMOUSEKEYS = 0x0037
SPI_GETACCESSTIMEOUT = 0x003C
SPI_SETACCESSTIMEOUT = 0x003D
SPI_GETHIGHCONTRAST = 0x0042
SPI_SETHIGHCONTRAST = 0x0043
SPI_GETSOUNDSENTRY = 0x0040
SPI_SETSOUNDSENTRY = 0x0041
SPI_GETSERIALKEYS = 0x003E
SPI_SETSERIALKEYS = 0x003F
SPI_GETSCREENREADER = 0x0046
SPI_SETSCREENREADER = 0x0047

# -----------------------------------------------------------------------------
# DWM API (Категория 7)
# -----------------------------------------------------------------------------
DWMWA_NCRENDERING_ENABLED = 1
DWMWA_NCRENDERING_POLICY = 2
DWMWA_TRANSITIONS_FORCEDISABLED = 3
DWMWA_ALLOW_NCPAINT = 4
DWMWA_CAPTION_BUTTON_BOUNDS = 5
DWMWA_NONCLIENT_RTL_LAYOUT = 6
DWMWA_FORCE_ICONIC_REPRESENTATION = 7
DWMWA_FLIP3D_POLICY = 8
DWMWA_EXTENDED_FRAME_BOUNDS = 9
DWMWA_HAS_ICONIC_BITMAP = 10
DWMWA_DISALLOW_PEEK = 11
DWMWA_EXCLUDED_FROM_PEEK = 12
DWMWA_CLOAK = 13
DWMWA_CLOAKED = 14
DWMWA_FREEZE_REPRESENTATION = 15
DWMWA_USE_IMMERSIVE_DARK_MODE = 20
DWMWA_WINDOW_CORNER_PREFERENCE = 33
DWMWA_BORDER_COLOR = 34
DWMWA_CAPTION_COLOR = 35
DWMWA_TEXT_COLOR = 36
DWMWA_VISIBLE_FRAME_BORDER_THICKNESS = 37
DWMWA_SYSTEMBACKDROP_TYPE = 38

# DWM Corner Preferences
DWMWCP_DEFAULT = 0
DWMWCP_DONOTROUND = 1
DWMWCP_ROUND = 2
DWMWCP_ROUNDSMALL = 3

# DWM System Backdrop Types
DWMSBT_AUTO = 0
DWMSBT_NONE = 1
DWMSBT_MAINWINDOW = 2  # Mica
DWMSBT_TRANSIENTWINDOW = 3  # Acrylic
DWMSBT_TABBEDWINDOW = 4  # Tabbed / Mica Alt

# -----------------------------------------------------------------------------
# System Colors (Категория 14)
# -----------------------------------------------------------------------------
COLOR_BACKGROUND = 1
COLOR_ACTIVECAPTION = 2
COLOR_INACTIVECAPTION = 3
COLOR_MENU = 4
COLOR_WINDOW = 5
COLOR_WINDOWFRAME = 6
COLOR_MENUTEXT = 7
COLOR_WINDOWTEXT = 8
COLOR_CAPTIONTEXT = 9
COLOR_HIGHLIGHT = 13
COLOR_HIGHLIGHTTEXT = 14
COLOR_INACTIVECAPTIONTEXT = 19

# -----------------------------------------------------------------------------
# Display Configuration API Topologies (Категория 12)
# -----------------------------------------------------------------------------
SDC_TOPOLOGY_INTERNAL = 0x00000001
SDC_TOPOLOGY_CLONE = 0x00000002
SDC_TOPOLOGY_EXTEND = 0x00000004
SDC_TOPOLOGY_EXTERNAL = 0x00000008
SDC_APPLY = 0x00000080
