# -*- coding: utf-8 -*-
# =============================================================================
# Process Name: Log Analyzer Engine & CLI Tool
# =============================================================================
# Description:
#   Parses, aggregates, and diagnoses application and system logs.
#   Provides structured summary, error clustering, frequency metrics,
#   and optional AI-driven synthesis using Gemini.
#
# File: analyze.py
# Project: ai-breadboard
# Package: .agents.skills.log-analyzer.scripts
# Author: hypo69
# Copyright: © 2026 hypo69
# =============================================================================

"""Log Analyzer Engine & CLI Tool.

Performs static and AI-assisted log analysis, error clustering,
and report generation for AI-Breadboard and related services.
"""

from __future__ import annotations

import argparse
import asyncio
import datetime
import json
import os
import re
import sys
import tempfile
from collections import Counter
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

# Determine workspace root dynamically
CURRENT_DIR = Path(__file__).resolve().parent
SKILL_ROOT = CURRENT_DIR.parent
PROJECT_ROOT = CURRENT_DIR.parents[2]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


@dataclass
class LogEntry:
    """Represents a single parsed log event.

    Attributes:
        timestamp: Extracted timestamp or empty string.
        level: Normalized log level (INFO, WARNING, ERROR, CRITICAL, DEBUG).
        message: Log event message text.
        source: Source file or logger name.
        traceback: Associated stack trace if present.
        raw_line: Original raw log line.
    """

    timestamp: str = ""
    level: str = "INFO"
    message: str = ""
    source: str = ""
    traceback: str = ""
    raw_line: str = ""


@dataclass
class AnalysisResult:
    """Summary and clustering result of log analysis.

    Attributes:
        total_lines: Total lines processed.
        total_events: Total individual events parsed.
        level_counts: Counter mapping level name to count.
        top_errors: List of most frequent error patterns.
        identified_issues: Extracted distinct issue descriptions.
        start_time: Earliest timestamp in analyzed scope.
        end_time: Latest timestamp in analyzed scope.
        ai_summary: Markdown text generated by AI model if enabled.
    """

    total_lines: int = 0
    total_events: int = 0
    level_counts: Dict[str, int] = field(default_factory=dict)
    top_errors: List[Dict[str, Any]] = field(default_factory=list)
    identified_issues: List[str] = field(default_factory=list)
    start_time: str = ""
    end_time: str = ""
    ai_summary: str = ""


class LogParser:
    """Parser and clusterer for text and JSON log formats."""

    LOG_PATTERN = re.compile(
        r"^(?P<timestamp>\d{4}-\d{2}-\d{2}[T\s]\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:[+-]\d{2}:?\d{2}|Z)?)"
        r"\s*(?:\[(?P<level>[A-Z]+)\]|(?P<level_alt>[A-Z]+))\s*"
        r"(?:\[(?P<source>[^\]]+)\])?\s*"
        r"(?P<message>.*)$",
        re.IGNORECASE,
    )

    def parse_text(self, text: str) -> List[LogEntry]:
        """Parse raw log text into structured LogEntry objects.

        Args:
            text: Raw multi-line log string.

        Returns:
            List[LogEntry]: Parsed list of entries.
        """
        entries: List[LogEntry] = []
        current_entry: Optional[LogEntry] = None
        traceback_lines: List[str] = []

        for line in text.splitlines():
            line_str = line.strip()
            if not line_str:
                continue

            match = self.LOG_PATTERN.match(line_str)
            if match:
                if current_entry is not None:
                    if traceback_lines:
                        current_entry.traceback = "\n".join(traceback_lines)
                        traceback_lines = []
                    entries.append(current_entry)

                level = (match.group("level") or match.group("level_alt") or "INFO").upper()
                current_entry = LogEntry(
                    timestamp=match.group("timestamp") or "",
                    level=level,
                    source=match.group("source") or "",
                    message=match.group("message") or "",
                    raw_line=line_str,
                )
            elif current_entry is not None:
                # Accumulate tracebacks or multi-line messages
                if "Traceback" in line_str or traceback_lines or "Error" in line_str:
                    traceback_lines.append(line_str)
                else:
                    current_entry.message += f" {line_str}"
            else:
                # Handle unformatted leading lines
                entries.append(LogEntry(message=line_str, raw_line=line_str))

        if current_entry is not None:
            if traceback_lines:
                current_entry.traceback = "\n".join(traceback_lines)
            entries.append(current_entry)

        return entries

    def parse_json_lines(self, text: str) -> List[LogEntry]:
        """Parse JSON Lines formatted logs into LogEntry objects.

        Args:
            text: JSON Lines content.

        Returns:
            List[LogEntry]: Parsed entries.
        """
        entries: List[LogEntry] = []
        for line in text.splitlines():
            line_str = line.strip()
            if not line_str:
                continue
            try:
                data = json.loads(line_str)
                level = str(data.get("level", data.get("levelname", "INFO"))).upper()
                msg = str(data.get("message", data.get("msg", data.get("event", ""))))
                ts = str(data.get("timestamp", data.get("time", data.get("asctime", ""))))
                src = str(data.get("logger", data.get("name", data.get("module", ""))))
                tb = str(data.get("exc_info", data.get("traceback", data.get("exception", ""))))
                entries.append(
                    LogEntry(
                        timestamp=ts,
                        level=level,
                        message=msg,
                        source=src,
                        traceback=tb if tb != "None" else "",
                        raw_line=line_str,
                    )
                )
            except json.JSONDecodeError:
                entries.extend(self.parse_text(line_str))
        return entries


class LogAnalyzer:
    """Analyzes collections of log entries and extracts metrics and patterns."""

    def __init__(self, parser: Optional[LogParser] = None) -> None:
        """Initialize LogAnalyzer.

        Args:
            parser: Custom LogParser instance or default.
        """
        self.parser = parser or LogParser()

    def analyze_entries(self, entries: List[LogEntry]) -> AnalysisResult:
        """Analyze a list of parsed log entries.

        Args:
            entries: List of LogEntry objects.

        Returns:
            AnalysisResult: Computed metrics and grouped issues.
        """
        if not entries:
            return AnalysisResult()

        level_counts: Counter[str] = Counter()
        error_signatures: Counter[str] = Counter()
        timestamps = [e.timestamp for e in entries if e.timestamp]

        for entry in entries:
            level_counts[entry.level] += 1
            if entry.level in ("ERROR", "CRITICAL", "EXCEPTION") or entry.traceback:
                sig = self._extract_signature(entry)
                error_signatures[sig] += 1

        top_errors = [
            {"signature": sig, "count": count}
            for sig, count in error_signatures.most_common(10)
        ]

        return AnalysisResult(
            total_lines=len(entries),
            total_events=len(entries),
            level_counts=dict(level_counts),
            top_errors=top_errors,
            identified_issues=[item["signature"] for item in top_errors],
            start_time=timestamps[0] if timestamps else "",
            end_time=timestamps[-1] if timestamps else "",
        )

    def _extract_signature(self, entry: LogEntry) -> str:
        """Extract a normalized error signature for grouping.

        Args:
            entry: LogEntry instance.

        Returns:
            str: Normalized signature string.
        """
        text = entry.message
        if entry.traceback:
            tb_lines = [l.strip() for l in entry.traceback.splitlines() if l.strip()]
            if tb_lines:
                text = f"{tb_lines[-1]} | {text}"

        # Strip hex addresses, memory locations, UUIDs, and numbers for clustering
        text = re.sub(r"0x[0-9a-fA-F]+", "0x...", text)
        text = re.sub(
            r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
            "<UUID>",
            text,
        )
        text = re.sub(r"\b\d+\b", "<N>", text)
        return text[:160].strip()


async def run_ai_synthesis(
    log_content: str, result: AnalysisResult, custom_prompt: Optional[str] = None
) -> str:
    """Generate AI diagnosis and remediation recommendations.

    Args:
        log_content: Raw or truncated log sample.
        result: Computed static metrics.
        custom_prompt: Optional tailored prompt.

    Returns:
        str: Markdown formatted diagnostic report.
    """
    try:
        from src.ai import GoogleGenerativeAI

        api_key_names = [
            n.strip()
            for n in os.getenv("GEMINI_API_KEY_NAMES", "").split(",")
            if n.strip()
        ]
        if not api_key_names:
            return "_AI synthesis unavailable: GEMINI_API_KEY_NAMES not configured in environment._"

        ai = GoogleGenerativeAI(
            api_key_names=api_key_names,
            system_instruction=(
                "You are an expert site reliability engineer and log diagnostics assistant. "
                "Analyze errors, root causes, system impact, and provide actionable fixes."
            ),
        )

        metrics_summary = (
            f"Total events: {result.total_events}, "
            f"Levels: {json.dumps(result.level_counts)}, "
            f"Top Issues: {json.dumps(result.top_errors, indent=2)}"
        )

        prompt = custom_prompt or (
            f"Please analyze the following system log diagnostic data:\n\n"
            f"### Static Metrics:\n{metrics_summary}\n\n"
            f"### Log Content Sample:\n```text\n{log_content[:20000]}\n```\n\n"
            f"Provide a structured Markdown report with:\n"
            f"1. Executive Summary\n"
            f"2. Root Cause Analysis of High Severity Errors\n"
            f"3. Anomalies and Recurring Patterns\n"
            f"4. Recommended Remediation Steps"
        )

        response = await ai.ask(prompt)
        return response or "_No response received from AI model._"
    except Exception as ex:
        return f"_AI diagnostic execution failed: {ex}_"


def format_markdown_report(result: AnalysisResult, target_name: str) -> str:
    """Format an analysis result into a clean markdown document.

    Args:
        result: AnalysisResult object.
        target_name: Identifier or filename analyzed.

    Returns:
        str: Full markdown report content.
    """
    now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        f"# 📊 Log Analysis Report: `{target_name}`",
        f"**Generated:** {now_str}  ",
        f"**Time Window:** `{result.start_time or 'N/A'}` → `{result.end_time or 'N/A'}`",
        "",
        "## 📈 Event Metrics",
        f"- **Total Events:** {result.total_events}",
        f"- **Level Breakdown:**",
    ]

    for lvl, count in sorted(result.level_counts.items(), key=lambda x: x[1], reverse=True):
        badge = "🔴" if lvl in ("ERROR", "CRITICAL") else ("🟡" if lvl == "WARNING" else "🟢")
        lines.append(f"  - {badge} **{lvl}:** {count}")

    lines.append("")
    lines.append("## 🔍 Top Recurring Errors & Signatures")
    if result.top_errors:
        for idx, item in enumerate(result.top_errors, 1):
            lines.append(f"{idx}. `[{item['count']}x]` `{item['signature']}`")
    else:
        lines.append("✅ No recurring errors or exceptions detected.")

    if result.ai_summary:
        lines.append("")
        lines.append("---")
        lines.append("## 🤖 AI Diagnosis & Recommendations")
        lines.append(result.ai_summary)

    return "\n".join(lines)


def get_default_log_dir() -> Path:
    """Resolve the default system log directory for AI Breadboard.

    Returns:
        Path: Resolved logs directory path.
    """
    return Path(tempfile.gettempdir()) / "ai-breadboard" / "logs"


def get_default_reports_dir() -> Path:
    """Resolve the default reports directory for AI Breadboard.

    Returns:
        Path: Resolved reports directory path.
    """
    return Path(tempfile.gettempdir()) / "ai-breadboard" / "reports"


async def main_async(args: argparse.Namespace) -> int:
    """Asynchronous entry point for CLI log analysis.

    Args:
        args: Parsed CLI arguments.

    Returns:
        int: Exit status code (0 for success).
    """
    parser = LogParser()
    analyzer = LogAnalyzer(parser)

    log_dir = Path(args.log_dir) if args.log_dir else get_default_log_dir()
    files_to_process: List[Path] = []

    if args.file:
        file_path = Path(args.file)
        if not file_path.exists():
            print(f"❌ Error: Specified file not found: {file_path}", file=sys.stderr)
            return 1
        files_to_process.append(file_path)
    else:
        if log_dir.exists():
            files_to_process.extend(sorted(log_dir.glob("*.log")))
            json_log = log_dir / "log.json"
            if json_log.exists():
                files_to_process.append(json_log)

    if not files_to_process:
        print(f"ℹ️ No log files found in: {log_dir}")
        return 0

    combined_entries: List[LogEntry] = []
    combined_raw: List[str] = []

    print(f"📂 Analyzing {len(files_to_process)} log file(s)...")
    for fpath in files_to_process:
        try:
            content = fpath.read_text(encoding="utf-8", errors="ignore")
            if args.tail and args.tail > 0:
                lines = content.splitlines()[-args.tail :]
                content = "\n".join(lines)

            if fpath.name.endswith(".json") or fpath.name == "log.json":
                entries = parser.parse_json_lines(content)
            else:
                entries = parser.parse_text(content)

            combined_entries.extend(entries)
            combined_raw.append(f"=== File: {fpath.name} ===\n{content}\n")
            print(f"  - Read {fpath.name}: {len(entries)} events")
        except Exception as ex:
            print(f"  ⚠️ Failed to read {fpath.name}: {ex}", file=sys.stderr)

    if args.level:
        target_lvl = args.level.upper()
        combined_entries = [e for e in combined_entries if e.level == target_lvl]

    analysis_res = analyzer.analyze_entries(combined_entries)

    if args.ai:
        print("🤖 Requesting AI diagnostic synthesis...")
        raw_snippet = "\n".join(combined_raw)
        analysis_res.ai_summary = await run_ai_synthesis(raw_snippet, analysis_res)

    report_md = format_markdown_report(analysis_res, target_name="System Logs")

    if args.json:
        out_data = {
            "metrics": asdict(analysis_res),
            "report_markdown": report_md,
        }
        print(json.dumps(out_data, indent=2, ensure_ascii=False))
    else:
        print("\n" + report_md + "\n")

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(report_md, encoding="utf-8")
        print(f"✅ Report saved to: {out_path}")
    elif args.save_report:
        rep_dir = get_default_reports_dir()
        rep_dir.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        out_path = rep_dir / f"log_analysis_{timestamp}.md"
        out_path.write_text(report_md, encoding="utf-8")
        print(f"✅ Report saved to: {out_path}")

    return 0


def main() -> int:
    """Synchronous CLI entry point."""
    cli_parser = argparse.ArgumentParser(
        description="Log Analyzer Tool - Diagnose, cluster, and report system logs."
    )
    cli_parser.add_argument("--file", "-f", help="Specific log file path to analyze.")
    cli_parser.add_argument("--log-dir", "-d", help="Custom directory containing log files.")
    cli_parser.add_argument("--level", "-l", help="Filter by level (e.g. ERROR, WARNING, INFO).")
    cli_parser.add_argument("--tail", "-n", type=int, default=0, help="Analyze last N lines.")
    cli_parser.add_argument("--ai", action="store_true", help="Enable AI diagnostic report.")
    cli_parser.add_argument("--json", action="store_true", help="Output summary in JSON format.")
    cli_parser.add_argument("--output", "-o", help="Save markdown report to custom file path.")
    cli_parser.add_argument("--save-report", "-s", action="store_true", help="Save report to default reports dir.")

    parsed_args = cli_parser.parse_args()
    return asyncio.run(main_async(parsed_args))


if __name__ == "__main__":
    sys.exit(main())
